import LocalizedStrings from 'react-native-localization'

let strings = new LocalizedStrings({

  /*
  .########.##....##..######...##.......####..######..##.....##
  .##.......###...##.##....##..##........##..##....##.##.....##
  .##.......####..##.##........##........##..##.......##.....##
  .######...##.##.##.##...####.##........##...######..#########
  .##.......##..####.##....##..##........##........##.##.....##
  .##.......##...###.##....##..##........##..##....##.##.....##
  .########.##....##..######...########.####..######..##.....##
  */

  en: {
    authentication: {
      LogIn: 'Log In',
      TermsConditions: 'Terms & Conditions'
    },
    appCommon: {
      seeDetails: 'See Details',
      gender: "Gender",
      healthBackground: "Health Background",
      healthSmoker: "Are you a smoker?",
      healthHighBP: "Have you ever been diagnosed with high blood pressure?",
      healthDiabetes: "Do you have diabetes?",
      yes: "Yes",
      no: 'No',
      notAnswred: "Not Answred",
      medication: "Medication",
      next: "Next",
      comment: "Comment",
      send: "Send"
    },
    sidemenu: {
      myAssistant: "My Assistant",
      patient: "Patient",
      appointments: "Appointments",
      followup: "Follow-Up",
      consultationNotes: "Consultation Notes",
      blog: "Blog",
      followColleagues: "Follow Colleagues",
      inviteColleagues: "Invite Colleagues",
      chatColleagues: "Chat with Colleagues",
      events: "Events",
      betterMe: "Better Me",
      takePart: "Take Part",
      starmeUp: "StarMe Up",
      logout: "Log Out"
    },
    startScreen: {
      goodEvening: 'Good Evening',
      Pending: 'Pending',
      ToDo: 'To Do',
      Started: 'Started',
      Done: 'Done',
      resend: 'Resend',
      videocall: 'Video Call'
    },
    patientDetails: {
      birthdayDate: 'Birthday Date',
      temperature: "Temperature",
      cough: "Cough",
      completedOn: "Completed On",
      followupDay: "Follow-up Day"
    },
    settings: {
      settings: "Settings",
      viewProfile: "View your profile",
      events: "Events",
      batterMe: "Better Me",
      takePart: "Take Part",
      starmeUp: "StarMe Up",
      logout: "Logout"
    },
    batterMe: {
      requestFeedback: "Request Feedback",
      sendFeedback: "Send Feedback",
      feedbackRequests: "Feedback Requests",
      history: "History",
      suggestedColleagues: "Suggested Colleagues",
      yourCompetencies: "Your Competencies",
      agility: "Agility",
      orientation: "Orientation",
      relationships: "Relationships",
      creative: "Creative",
      ownership: "Ownership",
      proactive: "Proactive",
      service: "Service",
      opener: "Opener",
      emotionalIntelligence: "Emotional Intelligence"
    },
    patientList: {
      patient: 'Patient',
      showing: 'Showing:',
      activePatient: 'Active Patient',
      cancel: 'Cancel',
      select: 'Select',
      filter: 'Filter'
    },
    patientDetailsScreen: {
      patientDetails: 'Patient Details',
      enabled: 'Enabled',
      health: 'Health',
      profile: 'Profile',
      trackers: 'Trackers',
      medical: 'Medical',
      reports: 'Reports',
      journals: 'Journals',
      consultation: 'Consultation',
      notes: 'Notes',
      patient: 'Patient',
      payments: 'Payments'
    },
    healthProfile: {
      healthProfile: 'Health Profile',
      profile: 'Profile',
      trackers: 'Trackers',
      reports: 'Reports',
      enabled: 'Enabled',
      healthConditions: 'Health Conditions',
      medications: 'Medications',
      allergies: 'Allergies',
      socialHistory: 'Social History',
      familyMedicalHistory: 'Family Medical History',
      contraindications: 'Contraindications',
      hospitalizations: 'Hospitalizations',
      surgeryProcedure: 'Surgery/Procedure',
      vaccinations: 'Vaccinations',
      bloodPressure: 'Blood Pressure',
      bloodSuger: 'Blood Suger',
      cholesterol: 'Cholesterol',
      exercise: 'Exercise',
      food: 'Food',
      height: 'Height',
      jointStiffness: 'Joint Stiffness',
      oxygenLevel: 'Oxygen Level',
      pain: 'Pain',
      pulse: 'Pulse',
      respiratoryRates: 'Respiratory Rates',
      sleep: 'Sleep',
      temperature: 'Temperature',
      waistMeasurement: 'Waist Measurement',
      weight: 'Weight',
      noData: 'No Data',
      updateTracker: 'UPDATE TRACKER',
      noMedicle: 'No medical reports of this patients have been uploaded as yet.',
      addNew: 'ADD NEW'
    },
    healthConditionList: {
      healthCondition: 'Health Condition',
      showing: 'Showing:',
      all: 'All',
      ongoing: 'Ongoing',
      past: 'Past',
      VitaminB12Deficiency: 'Vitamin B12 deficiency',
      type1Diabetese: 'Type 1 diabetese (DM)',
      completed: 'Completed'
    },
    addHealthCondition: {
      addHealthCondition: 'Add Health Condition',
      save: 'Save',
      nameOfCondition: 'Name of Condition',
      nameOfConditionPlaceholder: 'e.g. Hypertension, Type || Diabetes',
      firstDiagnosedOn: 'First Diagnosed On',
      status: 'Status',
      ongoing: 'Ongoing',
      medicationTaken: 'Medication Taken',
      addMedication: 'Add Medication',
      treatedBy: 'Treated by',
      drName: 'Doctor\'s Name',
      notes: 'Notes'
    },
    medicationsList: {
      medications: 'Medications',
      showing: 'Showing:',
      allMedications: 'All Medications',
      ongoingMedications: 'Ongoing Medications',
      pastMedications: 'Past Medications',
    },
    addMedicationScreen: {
      addMedication: 'Add Medication',
      save: 'Save',
      medicationName: 'Medication Name',
      medicationPlaceholder: 'Enter name of medication',
      formOfMedicine: 'Form of Medicine',
      methodOfIntake: 'Method of intake',
      dosage: 'Dosage',
      quality: 'Quality',
      frequencyOfIntake: 'Frequency of intake',
      when: 'When',
      addAnotherDosage: 'ADD ANOTHER DOSAGE',
      addAnotherDosagePlaceholder: 'Enter any information related to your medication intake',
      duration: 'Duration',
      beforeMeals: 'Before Meals',
      withMeals: 'With Meals',
      afterMeals: 'After Meals',
      atBedtime: 'At Bedtime',
      morningAndEveningAfterMeals: 'Morning and Evening after meals',
      morningAndAfternoonAfterMeals: 'Morning and Afternoon after meals',
      afternoonAndEveningAfterMeals: 'Afternoon and Evening after meals',
      morningAndEveningBeforeMeals: 'Morning and Evening before meals',
      morningAndAfternoonBeforeMeals: 'Morning and Afternoon before meals',
      afternoonAndEveningBeforeMeals: 'Afternoon and Evening before meals',
      morningAfterMeals: 'Morning after meals',
      morningBeforeMeals: 'Morning before meals',
      afternoonAfterMeals: 'Afternoon after meals',
      afternoonBeforeMeals: 'Afternoon before meals',
      eveningBeforeMeans: 'Evening before means',
      morningWithMeals: 'Morning with meals',
      afternoonWithMeals: 'Afternoon with meals',
      eveningWithMeals: 'Evening with meals',
      oneHourAfterMeals: 'One hour after meals',
      oneHourBeforeMeals: 'One hour before meals',
      twoHourAfterMeals: 'Two hour after meals',
      halfHourBeforeMeals: 'Half hour before meals'
    },
    allergiesList: {
      allergies: 'Allergies',
      latexAllergy: 'Latex Allergy',
      cough: 'Cough'
    },
    addOptionsHealthProfile: {
      occupation: 'Occupation',
      education: 'Education',
      educationYear: 'Education Year',
      birthPlace: 'Birth Place',
      maritalStatus: 'Marital Status',
      children: 'Children',
      religion: 'Religion',
      generalDiet: 'General Diet',
      sexualOrientation: 'Sexual Orientation',
      smoking: 'Smoking',
      alcoholConsumption: 'Alcohol Consumption',
      substanceUse: 'Substance Use',
      exercise: 'Exercise',
      stressFactor: 'Stress Factor',
      languageSpoken: 'Language Spoken',
      secondaryLanguageSpoken: 'Secondary Language Spoken',
      addNew: 'ADD NEW',
      newTask: 'New Task',
      notifications: 'Notifications',
      allTasks: 'All Tasks',
      showing: 'Showing:',
      hcIntro: 'Add all known Health Conditions for this patient.',
      mediIntro: 'There are no medications matching this filter.',
      allergyIntro: 'Add all known allergies of this patient.',
      scIntro: 'Update known social history details.',
      familyIntro: 'Update the patient\'s family medical history.',
      conIntro: 'Add all known contraindications for this patient.',
      hospiIntro: 'Add history of past hospitalizations for this patient.',
      surIntro: 'Add details of surgeries and implants if any.',
      vaccineIntro: 'Add all known vaccinations taken by this patient.'
    },
    familyMedicalHistoryList: {
      familyMedicalHistory: 'Family Medical History'
    },
    addFamilyMedicalHistory: {
      addFamilyMedicalHistory: 'Add Family Medical History',
      save: 'Save',
      relationship: 'Relationship',
      notePlaceholder: 'e.g. has a history of high blood oressure and heart disease. He had undergone open heart surgery 8 years ago.',
      mother: 'Mother',
      father: 'Father',
      siblings: 'Siblings',
      grandPatents: 'Grand Patents',
      children: 'Children',
      others: 'Others',
      selectOne: 'Select One...'
    },
    contraindicationList: {
      contraindications: 'Contraindications'
    },
    addContraindication: {
      addContraindication: 'Add Contraindication',
      save: 'Save',
      description: 'Description',
      descPlaceholder: 'e.g. I was advised against taking a decongestant for sinusitis due to high BP'
    },
    hospitalizationList: {
      hospitalization: 'Hospitalization',
      treatedBy: 'Treated By:',
      for: 'For:',
      all: 'All',
      ongoing: 'Ongoing',
      past: 'Past'
    },
    AddHospitalization: {
      addHospitalization: 'Add Hospitalization',
      save: 'Save',
      admissionDate: 'Admission Date',
      startDate: 'Start Date',
      dischargeDate: 'Discharge Date',
      endDate: 'End Date',
      providerName: 'Provider Name',
      hospitalName: 'Hospital Name',
      respiratoryIllness: 'Respiratory illness',
      addAttchment: 'Add Attchments[Max size 5MB per file]'
    },
    surgeryList: {
      headerName: 'Surgery/Procedure',
      conductedOn: 'Conducted on:',
      operatedBy: 'Operated By:'
    },
    addSurguryProcedure: {
      headerName: 'Add Surgery/Procedure',
      save: 'Save',
      name: 'Name',
      allergyPlaceholder: 'e.g. Fitting pacemaker, Kidney stone removal...',
      conductedOn: 'Conducted on',
      implants: 'Implants/Support Devices',
      implantsPlaceholder: 'e.g. Pacemaker, Stent, Knee joint, etc',
      operatedBy: 'Operated by',
      operatedByPlaceholder: 'e.g. Dr. Gopan at Ortho Hospital, etc',
      notes: 'Notes'
    },
    vaccinationList: {
      vaccinationList: 'Vaccination List',
      vaccinatedOn: 'Vaccinated on:',
      vaccineName: 'Vaccine Name:'
    },
    addVaccinationList: {
      addVaccination: 'Add Vaccination',
      save: 'Save',
      vaccineTakenFor: 'Vaccine taken for',
      vaccinePlaceholder: 'e.g. Hopatits B, Polio, Tetanus, etc',
      takenOn: 'Taken On',
      vaccineName: 'Vaccine Name',
      vaccinePlaceholder: 'e.g. HepB, IPV, Tdap, etc',
      vaccineDetails: 'Veccine Details',
      veccineDetailPlaceholder: 'e.g. Pneumovax (Merck), Enterix(GiaxoSmit...',
      lotNumber: 'Lot Number',
      lotNu: 'e.g. AB0CA007A',
      notes: 'Notes'
    },
    addMedicalReport: {
      addMedicalReport: 'Add Medical Report',
      save: 'Save',
      nameOfMedicalReport: 'Name of Medical Report',
      testTitle: 'TSH - e.g. High, T4 - Normal',
      testTitlePlaceholder: 'e.g. Chest x-ray, Thyrod blood test etc.',
      prescribedBy: 'Prescribed By',
      testCenter: 'Test Center',
      addAttachment: 'Add Attchments[Max size 5MB per file]',
      uploadAttachment: 'Upload\nAttachment',
      notes: 'Notes'
    },
    addPatient: {
      addPatient: 'Add Patient',
      save: 'Save',
      mobileNumber: 'Mobile Number',
      firstName: 'First Name',
      lastName: 'Last Name',
      dob: 'Date of birth',
      gender: 'Gender',
      patientId: 'Patient ID (optional)'
    },
    consultationNotes: {
      consultationNotes: 'Consultation Notes',
      enabled: 'Enabled',
      showing: 'Showing:',
      allConsultations: 'All Consultations',
      filter: 'Filter',
      introText: 'You have not logged any online or clinic Consultations as yet for this patient.',
      logConsultation: 'LOG CONSULTATION',
      selectMonitoringPlanning: 'Select Monitoring Planning',
      allMonitoring: 'All monitoring plans have been assigned to this patient. To add a new monitoring plan to your appm visit the admin portal from the web.',
      clinicConsultation: 'Clinic Consultation',
      reasonForConsultation: 'Reason for Consultation',
      clinicSummary: 'Clinic Summary',
      visibleToPatient: 'Visible to Patient',
      viewAttachment: 'View Attachment',
      prescriptions: 'Prescriptions',
      goals: 'Goals',
      attachments: 'Attachments',
      done: 'Done'
    },
    filterConsultationNotes: {
      consultationNotes: 'Consultation Notes',
      reset: 'Reset',
      filterByProvider: 'Filter By Provider',
      filterByConsultationType: 'Filter By Consultation Type',
      filterByConsultationLocation: 'Filter By Consultation Location',
      showConsultation: 'Show Consultation',
      all: 'All',
      for7Days: 'For 7 Days',
      for30Days: 'For 30 Days',
      byDate: 'By Date',
      apply: 'APPLY',
      allConsultations: 'All Consultations',
      clinicConsultations: 'Clinic Consultations',
      videoConsultations: 'Video Consultations',
      patientQueationFollowup: 'Patient Queation Followup',
      remoteMonitoringFollowup: 'Remote Monitoring Followup',
      medicalReportReview: 'Medical Report Review',
      from: 'From',
      to: 'To'
    },
    appointmentList: {
      appointments: 'Appointments',
      new: 'NEW',
      confirmed: 'CONFIRMED',
      confirm: 'CONFIRM',
      reschedule: 'RESCHEDULE',
      cancel: 'CANCEL',
      rescheduleAppointment: 'Reschedule Appointment',
      rescheduledDate: 'Rescheduled Date',
      rescheduledTime: 'Rescheduled Time',
      noSlots: 'No slots available for the choosed date',
      rescheduleNote: 'Rescheduled Note to Patient',
      submit: 'SUBMIT',
      confirmAppointmtent: 'Confirm Appointment(optional)',
      selectAppointmtntType: 'Select Appointmtnt Type',
      clinicConsultation: 'Clinic Consultation',
      videoConsultation: 'Video Consultation'
    },
    appointmentFilter: {
      all: 'All',
      confirmed: 'Confirmed',
      newOrReschedule: 'New or Reschedule',
      cancelled: 'Cancelled',
      concluded: 'Concluded',
      video: 'Video',
      clinic: 'Clinic',
      allPracticeLocation: 'All Practice Location',
      allDepartment: 'All Department',
      allServices: 'All Services',
      VideoCons: 'Video Consultation(15) min',
      appointmentFilter: 'Appointment Filter',
      clinicSummary: 'Clinic Summary',
      practiceLocation: 'Practice Location',
      department: 'Department',
      healthcareProvider: 'Healthcare Provider',
      service: 'Service',
      appointmentStatus: 'Appointment Status',
      clear: 'Clear',
      apply: 'Apply'
    },
    setClinicConsultation: {
      setClinicConsultation: 'Set Clinic Consultation',
      done: 'Done',
      service: 'Service',
      practiceLocation: 'Practice Location',
      showConsultationTimings: 'Show Consultation Timings',
      from: 'From',
      to: 'To',
      patient: 'Patient',
      phonenumber: 'Phone number',
      reasonforAppointment: 'Reason for Appointment',
      reasonPlaceholder: 'Enter a reason for setting the patient appointment'
    },
    consultationTimings: {
      monday: 'Monday',
      tuesday: 'Tuesday',
      wednesday: 'Wednesday',
      thursday: 'Thursday',
      friday: 'Friday',
      saturday: 'Saturday',
      sunday: 'Sunday',
      timing: '*Timing shown in (IST=UTC+05:30)',
      consultationTimings: 'Consultation Timings',
      done: 'Done',
      service: 'Service',
      practiceLocation: 'Practice Location'
    },
    userProfile: {
      profile: "Profile",
      yourDetails: "Your Details",
      contactInfo: "Contact Info",
      manager: "Manager",
      phoneNumber: "Phone Number",
      about: "About",
      dashboard: "Dashboard",
      experience: "Experience",
      accomplishment: "Accomplishment",
      course: "Course",
      language: "Language",
      projects: "Projects",
      interests: "Inrerests",
      yourDashboard: "Your Dashboard",
      privateToYou: "Private to You",
      whoViewedYourProfile: "Who viewed your profile",
      postViews: "Post Views",
      searchAppearance: "Search Appearance",
      carrerInterests: "Career Interests",
      chooseTypeOpportunity: "Choose the types of opportunities you'd like to be connected with",
      salaryInsights: "Salary Insights",
      salaryInsightsNote: "See how salary compares to others in the community",
      editProfile: "Edit Profile",
      firstName: "First Name",
      lastName: "Last Name",
      headline: "Headline",
      countryRegion: "Country/Region",
      provinceState: "Province/State",
      cityDistrice: "City/District",
      save: "Save",
      takePhoto: "Take Photo...",
      chooseFromGallery: "Choose from Library",
      cancel: "Cancel",
      addExperience: "Add Experience",
      title: "Title",
      employmentType: "Employment Type",
      location: "Location",
      currentlyWorking: "I am currently working in this role",
      startDate: "Start Date",
      endDate: "End Date",
      description: "Description",
      Connections: "Connections"
    },
    betterMe: {
      requestFeedback: 'Request Feedback',
      sendFeedback: 'Send Feedback',
      feedbackRequests: 'Feedback Requests',
      history: 'History',
      betterMe: 'Better Me'
    },
    sendFeedback: {
      suggestedColleagues: 'Suggested Colleagues',
      findColleagues: 'Find Colleagues',
      sendFeedback: 'Send Feedback'
    },
    feedbackRequests: {
      answerRequest: 'Answer Request'
    },
    history: {
      received: 'Received',
      sent: 'Sent',
      loading: 'Loading'
    },
    takePart: {
      takePart: 'Take Part',
      whenDo: 'When do you prefer to do the Business workshop?',
      beingAble: 'Being able to generate and identify more ideas helps companies grow more quickly, stay relevant, and drive new trends.'
    },
    createTakePart: {
      createTakePart: 'Create Take Part',
      create: 'Create',
      chooseACardType: 'Choose a card type',
      tellUsYourWhy: 'Tell us your why',
      selectGroup: 'Select group to share card',
      what: 'WHAT?',
      why: 'WHY?',
      who: 'WHO?',
    },
    createCardReason: {
      createardReason: 'Why are you creating this card?',
      ansYes: 'Ans: Eg. Yes',
      ansNo: 'Ans: Eg. No',
      giveMoreDetails: 'Give More detail to this card',
      cardDetails: 'Card Details'
    },
    selectGroups: {
      chooseCardType: 'Choose Card Type',
      next: 'Next'
    },
    starMeUpChooseType: {
      sendAStar: 'Send A Star',
      selectedColleague: 'Selected Colleague',
      selectedGroups: 'Selected Groups/Colleague',
      placeHolder: 'Please tell us the reason you are recognizing your colleague',
      writeAComment: 'Write A Comment',
      send: 'Send'
    },
    starMeUpDashboard: {
      kudos: 'KUDOS',
      actEthecally: 'ACT ETHICALLY',
      teamPlayer: 'TEAM PLAYER',
      constantlyInnovate: 'CONSTANTLY INNOVATE',
      excellence_in_your_work: 'EXCELLENCE IN YOUR WORK',
      think_big: 'THINK BIG',
      have_fun: 'HAVE FUN',
      sendBy: 'send By',
      thisIsTextComment: 'This is text comment'
    },
    addGroup: {
      postToGroup: 'Post to group',
      selectColleague: 'Select Colleague',
      next: 'Next',
      startBy: 'Start by picking members for your groups.',
      emailPlaceholder: 'Type an email address'
    },
    createGroup: {
      create: 'Create',
      groupName: 'Group Name',
      financeLeadPlaceholder: 'Ex. Finance Leads',
      groupType: 'Group type and privacy',
      description: 'Description (Optional)',
      descriptionPlaceholder: 'Tell your member what your group is for eg. team planning, or organising a space mission.',
      groupMembers: 'Group Members'
    },
    events: {
      events: 'Events',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      previous: 'Previous',
      participents: 'Participents'
    },
    createEvent: {
      createEvent: 'CreateEvent',
      selectAvatar: 'Select Avatar',
      generalTeamMeeting: 'General Team Meeting',
      startDate: 'Start Date',
      startTime: 'Start Time',
      pickTime: 'Pick a time',
      endDate: 'End Date',
      endTime: 'End Time',
      location: 'Location',
      description: 'Description',
      guestCan: 'Guests can invite coworkers',
      cancle: 'CANCLE',
      create: 'CREATE',
      eventName: 'Event Name',
      addPhoto: 'ADD PHOTO'
    },
    eventDetails: {
      going: 'Going',
      mayBe: 'Maybe',
      invited: 'Invited',
      saySomething: 'Say Something...',
      photo: 'Photo',
      recentActivity: 'RECENT ACTIVITY',
      joinPod: 'Join Pod',
      attending: 'Attending :'
    },
    updateStatus: {
      updateStatus: 'Update Status',
      post: 'Post',
      photoVideo: 'Photo/Video/Screenshot',
      goLive: 'Go Live',
      checkIn: 'Check In',
      feelingActivity: 'Feeling/Activity/Sticker',
      tagFriends: 'Tag Friends',
      whatsOnYourMind: 'Whats on your mind?'
    },
    tagMembers: {
      tagMembers: 'Tag Members',
      done: 'DONE',
      searchGroups: 'Search Groups'
    },
    inviteColleague: {
      findPhone: 'Find phone contacts',
      pendingInvites: 'Pending Invites',
      invite: 'INVITE',
      inviteColleague: 'Invite Colleague',
      enterEmail: 'Type an email address'
    },
    peopleToFollow: {
      peopleToFollow: 'People To Follow'
    },
    home: {
      newsFeed: 'News Feed',
      writePost: 'Write Post'
    },
    postToGroup: {
      postToGroup: 'Post to a group',
      searchGroups: 'Search Groups',
      yourTopGroups: 'Your top groups',
      commonDiscussion: 'Common Discussion',
      socialDiscussion: 'Social Discussion',
      general: 'General',
      flowDiscussion: 'Flow Discussion',
      uiUx: 'UI/UX'
    }
  },

  /*
  ..######...##.....##.......##....###....########.....###....########.####
  .##....##..##.....##.......##...##.##...##.....##...##.##......##.....##.
  .##........##.....##.......##..##...##..##.....##..##...##.....##.....##.
  .##...####.##.....##.......##.##.....##.########..##.....##....##.....##.
  .##....##..##.....##.##....##.#########.##...##...#########....##.....##.
  .##....##..##.....##.##....##.##.....##.##....##..##.....##....##.....##.
  ..######....#######...######..##.....##.##.....##.##.....##....##....####
  */

  gu: {
    authentication: {
      LogIn: 'પ્રવેશ કરો',
      TermsConditions: 'શરતો અને નિયમો'
    },
    appCommon: {
      seeDetails: 'વિગતો જુઓ',
      gender: "લિંગ",
      healthBackground: "આરોગ્ય પૃષ્ઠભૂમિ",
      healthSmoker: "તમે ધૂમ્રપાન કરનાર છો?",
      healthHighBP: "શું તમને ક્યારેય હાઈ બ્લડ પ્રેશર હોવાનું નિદાન થયું છે?",
      healthDiabetes: "શું તમને ડાયાબિટીઝ છે?",
      yes: "હા",
      no: 'ના',
      notAnswred: "જવાબ આપ્યો નથી",
      medication: "દવાઓ",
      next: "આગળ",
      comment: "ટિપ્પણી",
      send: "મોકલો"
    },
    sidemenu: {
      myAssistant: "My Assistant",
      patient: "Patient",
      appointments: "Appointments",
      followup: "Follow-Up",
      consultationNotes: "Consultation Notes",
      blog: "Blog",
      followColleagues: "Follow Colleagues",
      inviteColleagues: "Invite Colleagues",
      chatColleagues: "Chat with Colleagues",
      events: "Events",
      betterMe: "Better Me",
      takePart: "Take Part",
      starmeUp: "StarMe Up",
      logout: "Log Out"
    },
    startScreen: {
      goodEvening: 'શુભ સાંજ',
      Pending: 'બાકી',
      ToDo: 'શું કરવું',
      Started: 'શરૂ કર્યું',
      Done: 'થઈ ગયું',
      resend: 'ફરીથી મોકલો',
      videocall: 'વિડિઓ કૉલ'
    },
    patientDetails: {
      birthdayDate: 'જન્મદિવસની તારીખ',
      temperature: "તાપમાન",
      cough: "ખાંસી",
      completedOn: "પૂર્ણ થયું",
      followupDay: "ફોલો-અપ ડે"
    },
    settings: {
      settings: "સેટિંગ્સ",
      viewProfile: "તમારી પ્રોફાઇલ જુઓ",
      events: "ઘટનાઓ",
      batterMe: "બેટર મી",
      takePart: "ટેક પાર્ટ",
      starmeUp: "સ્ટારમી અપ",
      logout: "લૉગ આઉટ"
    },
    batterMe: {
      requestFeedback: "વિનંતી પ્રતિસાદ",
      sendFeedback: "પ્રતિસાદ મોકલ",
      feedbackRequests: "પ્રતિસાદ વિનંતીઓ",
      history: "ઇતિહાસ",
      suggestedColleagues: "સૂચવેલ સાથીઓ",
      yourCompetencies: "તમારી યોગ્યતા",
      agility: "ચપળતા",
      orientation: "અભિગમ",
      relationships: "સંબંધો",
      creative: "સર્જનાત્મક",
      ownership: "માલિકી",
      proactive: "સક્રિય",
      service: "સેવા",
      opener: "ઓપનર",
      emotionalIntelligence: "ભાવનાત્મક બુદ્ધિ"
    },
    patientList: {
      patient: 'દર્દી',
      showing: 'દર્શાવે:',
      activePatient: 'સક્રિય દર્દી',
      cancel: 'રદ કરો',
      select: 'પસંદ કરો',
      filter: 'ફિલ્ટર કરો'
    },
    patientDetailsScreen: {
      patientDetails: 'દર્દીની વિગતો',
      enabled: 'સક્ષમ',
      health: 'આરોગ્ય',
      profile: 'પ્રોફાઇલ',
      trackers: 'ટ્રેકર્સ',
      medical: 'તબીબી',
      reports: 'અહેવાલો',
      journals: 'જર્નલ',
      consultation: 'પરામર્શ',
      notes: 'નોંધો',
      patient: 'દર્દી',
      payments: 'ચુકવણીઓ'
    },
    healthProfile: {
      healthProfile: 'આરોગ્ય પ્રોફાઇલ',
      profile: 'પ્રોફાઇલ',
      trackers: 'ટ્રેકર્સ',
      reports: 'અહેવાલો',
      enabled: 'સક્ષમ',
      healthConditions: 'આરોગ્યની સ્થિતિ',
      medications: 'દવાઓ',
      allergies: 'એલર્જી',
      socialHistory: 'સામાજિક ઇતિહાસ',
      familyMedicalHistory: 'કૌટુંબિક તબીબી ઇતિહાસ',
      contraindications: 'બિનસલાહભર્યું',
      hospitalizations: 'હોસ્પિટલમાં દાખલ',
      surgeryProcedure: 'શસ્ત્રક્રિયા / કાર્યવાહી',
      vaccinations: 'રસીકરણો',
      bloodPressure: 'લોહિનુ દબાણ',
      bloodSuger: 'બ્લડ સુગર',
      cholesterol: 'કોલેસ્ટરોલ',
      exercise: 'કસરત',
      food: 'ખોરાક',
      height: '.ંચાઈ',
      jointStiffness: 'સંયુક્ત જડતા',
      oxygenLevel: 'ઓક્સિજન સ્તર',
      pain: 'પીડા',
      pulse: 'પલ્સ',
      respiratoryRates: 'શ્વસન દર',
      sleep: 'ઊંઘ',
      temperature: 'તાપમાન',
      waistMeasurement: 'કમર માપન',
      weight: 'વજન',
      noData: 'કોઈ ડેટા નથી',
      updateTracker: 'ટ્રેકર અપડેટ કરો',
      noMedicle: 'હજી સુધી આ દર્દીઓના કોઈ તબીબી અહેવાલો અપલોડ કરવામાં આવ્યાં નથી.',
      addNew: 'નવો ઉમેરો'
    },
    healthConditionList: {
      healthCondition: 'આરોગ્યની સ્થિતિ',
      showing: 'દર્શાવે:',
      all: 'બધા',
      ongoing: 'ચાલુ છે',
      past: 'ભૂતકાળ',
      VitaminB12Deficiency: 'વિટામિન બી 12 ની ઉણપ',
      type1Diabetese: 'પ્રકાર 1 ડાયાબિટીસ (ડીએમ)',
      completed: 'પૂર્ણ'
    },
    addHealthCondition: {
      addHealthCondition: 'આરોગ્યની સ્થિતિ ઉમેરો',
      save: 'સાચવો',
      nameOfCondition: 'શરતનું નામ',
      nameOfConditionPlaceholder: 'દા.ત. હાયપરટેન્શન, પ્રકાર || ડાયાબિટીસ',
      firstDiagnosedOn: 'પ્રથમ નિદાન ચાલુ',
      status: 'સ્થિતિ',
      ongoing: 'ચાલુ છે',
      medicationTaken: 'દવા લીધી',
      addMedication: 'દવા ઉમેરો',
      treatedBy: 'દ્વારા સારવાર આપવામાં આવે છે',
      drName: 'ડોક્ટરનું નામ',
      notes: 'નોંધો'
    },
    medicationsList: {
      medications: 'દવાઓ',
      showing: 'દર્શાવે:',
      allMedications: 'બધી દવાઓ',
      ongoingMedications: 'ચાલુ દવાઓ',
      pastMedications: 'ભૂતકાળની દવાઓ',
    },
    addMedicationScreen: {
      addMedication: 'દવા ઉમેરો',
      save: 'સાચવો',
      medicationName: 'દવા નામ',
      medicationPlaceholder: 'દવા નામ દાખલ કરો',
      formOfMedicine: 'દવાના સ્વરૂપ',
      methodOfIntake: 'સેવનની રીત',
      dosage: 'ડોઝ',
      quality: 'ગુણવત્તા',
      frequencyOfIntake: 'સેવનની આવર્તન',
      when: 'ક્યારે',
      addAnotherDosage: 'બીજી માત્રા ઉમેરો',
      addAnotherDosagePlaceholder: 'તમારા દવાના સેવનથી સંબંધિત કોઈપણ માહિતી દાખલ કરો',
      duration: 'અવધિ',
      beforeMeals: 'ભોજન પહેલાં',
      withMeals: 'ભોજન સાથે',
      afterMeals: 'જમ્યા પછી',
      atBedtime: 'સૂવાના સમયે',
      morningAndEveningAfterMeals: 'સવાર અને જમ્યા પછી સાંજ',
      morningAndAfternoonAfterMeals: 'સવાર અને બપોરે જમ્યા પછી',
      afternoonAndEveningAfterMeals: 'જમ્યા પછી બપોરે અને સાંજે',
      morningAndEveningBeforeMeals: 'ભોજન પહેલાં સવારે અને સાંજે',
      morningAndAfternoonBeforeMeals: 'સવાર અને બપોરના ભોજન પહેલાં',
      afternoonAndEveningBeforeMeals: 'ભોજન પહેલાં બપોરે અને સાંજે',
      morningAfterMeals: 'જમ્યા પછી સવારે',
      morningBeforeMeals: 'ભોજન પહેલાં સવારે',
      afternoonAfterMeals: 'જમ્યા પછી બપોરે',
      afternoonBeforeMeals: 'જમ્યા પહેલા બપોર પછી',
      eveningBeforeMeans: 'અર્થ પહેલાં સાંજે',
      morningWithMeals: 'ભોજન સાથે સવાર',
      afternoonWithMeals: 'બપોરે ભોજન સાથે',
      eveningWithMeals: 'ભોજન સાથે સાંજ',
      oneHourAfterMeals: 'જમ્યા પછી એક કલાક',
      oneHourBeforeMeals: 'ભોજન પહેલાં એક કલાક',
      twoHourAfterMeals: 'જમ્યા પછી બે કલાક',
      halfHourBeforeMeals: 'ભોજન પહેલાં અડધો કલાક'
    },
    allergiesList: {
      allergies: 'એલર્જી',
      latexAllergy: 'લેટેક્સ એલર્જી',
      cough: 'ખાંસી'
    },
    addOptionsHealthProfile: {
      occupation: 'વ્યવસાય',
      education: 'શિક્ષણ',
      educationYear: 'શિક્ષણ વર્ષ',
      birthPlace: 'જન્મ સ્થળ',
      maritalStatus: 'વૈવાહિક સ્થિતિ',
      children: 'બાળકો',
      religion: 'ધર્મ',
      generalDiet: 'સામાન્ય આહાર',
      sexualOrientation: 'જાતીય દિશા',
      smoking: 'ધૂમ્રપાન',
      alcoholConsumption: 'આલ્કોહોલનો વપરાશ',
      substanceUse: 'પદાર્થ ઉપયોગ',
      exercise: 'કસરત',
      stressFactor: 'તણાવ પરિબળ',
      languageSpoken: 'ભાષા બોલે છે',
      secondaryLanguageSpoken: 'માધ્યમિક ભાષા બોલાય છે',
      addNew: 'નવો ઉમેરો',
      newTask: 'નવું કાર્ય',
      notifications: 'સૂચનાઓ',
      allTasks: 'બધા કાર્યો',
      showing: 'દર્શાવે:',
      hcIntro: 'આ દર્દી માટે જાણીતી આરોગ્યની શરતો ઉમેરો.',
      mediIntro: 'આ ફિલ્ટર સાથે મેળ ખાતી કોઈ દવાઓ નથી.',
      allergyIntro: 'આ દર્દીની બધી જાણીતી એલર્જી ઉમેરો.',
      scIntro: 'જાણીતા સામાજિક ઇતિહાસની વિગતોને અપડેટ કરો.',
      familyIntro: 'દર્દીના કૌટુંબિક તબીબી ઇતિહાસને અપડેટ કરો.',
      conIntro: 'આ દર્દી માટે બધા જાણીતા contraindication ઉમેરો.',
      hospiIntro: 'આ દર્દી માટે પાછલા હોસ્પિટલમાં દાખલ થવાનો ઇતિહાસ ઉમેરો.',
      surIntro: 'શસ્ત્રક્રિયાઓ અને પ્રત્યારોપણની વિગતો ઉમેરો જો કોઈ હોય તો.',
      vaccineIntro: 'આ દર્દી દ્વારા લેવામાં આવતી તમામ જાણીતી રસીઓ ઉમેરો.'
    },
    familyMedicalHistoryList: {
      familyMedicalHistory: 'કૌટુંબિક તબીબી ઇતિહાસ'
    },
    addFamilyMedicalHistory: {
      addFamilyMedicalHistory: 'કૌટુંબિક તબીબી ઇતિહાસ ઉમેરો',
      save: 'સાચવો',
      relationship: 'સંબંધ',
      notePlaceholder: 'દા.ત. હાઈ બ્લડ પ્રેશર અને હૃદય રોગનો ઇતિહાસ છે. 8 વર્ષ પહેલા તેની ઓપન હાર્ટ સર્જરી કરાઈ હતી.',
      mother: 'માતા',
      father: 'પિતા',
      siblings: 'ભાઈ-બહેન',
      grandPatents: 'ગ્રાન્ડ પેટન્ટ્સ',
      children: 'બાળકો',
      others: 'અન્ય',
      selectOne: 'એક પસંદ કરો...'
    },
    contraindicationList: {
      contraindications: 'બિનસલાહભર્યું'
    },
    addContraindication: {
      addContraindication: 'બિનસલાહભર્યું ઉમેરો',
      save: 'સાચવો',
      description: 'વર્ણન',
      descPlaceholder: 'દા.ત. હાઈ બીપીને કારણે મને સિનુસાઇટિસ માટે ડીકોન્જેસ્ટંટ લેવાની સલાહ આપવામાં આવી હતી'
    },
    hospitalizationList: {
      hospitalization: 'હોસ્પિટલમાં દાખલ',
      treatedBy: 'દ્વારા સારવાર:',
      for: 'માટે:',
      all: 'બધા',
      ongoing: 'ચાલુ છે',
      past: 'ભૂતકાળ'
    },
    AddHospitalization: {
      addHospitalization: 'હોસ્પિટલમાં દાખલ કરો',
      save: 'સાચવો',
      admissionDate: 'પ્રવેશ તારીખ',
      startDate: 'પ્રારંભ તારીખ',
      dischargeDate: 'ડિસ્ચાર્જ તારીખ',
      endDate: 'અંતિમ તારીખ',
      providerName: 'પ્રદાતા નામ',
      hospitalName: 'હોસ્પિટલ નામ',
      respiratoryIllness: 'શ્વસન માંદગી',
      addAttchment: 'જોડાણો ઉમેરો [ફાઇલ દીઠ મહત્તમ કદ 5MB]'
    },
    surgeryList: {
      headerName: 'શસ્ત્રક્રિયા / કાર્યવાહી',
      conductedOn: 'હાથ ધરવામાં:',
      operatedBy: 'સંચાલિત:'
    },
    addSurguryProcedure: {
      headerName: 'શસ્ત્રક્રિયા / કાર્યવાહી ઉમેરો',
      save: 'સાચવો',
      name: 'નામ',
      allergyPlaceholder: 'દા.ત. ફિટિંગ પેસમેકર, કિડની પથ્થર દૂર ...',
      conductedOn: 'પર હાથ ધરવામાં આવેલ',
      implants: 'પ્રત્યારોપણ / સપોર્ટ ઉપકરણો',
      implantsPlaceholder: 'દા.ત. પેસમેકર, સ્ટેન્ટ, ઘૂંટણની સંયુક્ત, વગેરે',
      operatedBy: 'દ્વારા સંચાલિત',
      operatedByPlaceholder: 'દા.ત. ઓર્થો હોસ્પિટલ, વગેરેમાં ગોપન ડો',
      notes: 'નોંધો'
    },
    vaccinationList: {
      vaccinationList: 'રસીકરણની સૂચિ',
      vaccinatedOn: 'રસીકરણ આના પર:',
      vaccineName: 'રસી નામ:'
    },
    addVaccinationList: {
      addVaccination: 'રસીકરણ ઉમેરો',
      save: 'સાચવો',
      vaccineTakenFor: 'રસી લેવામાં આવી છે',
      vaccinePlaceholder: 'દા.ત. હોપેટિટ્સ બી, પોલિયો, ટિટાનસ, વગેરે',
      takenOn: 'પર લેવામાં',
      vaccineName: 'રસી નામ',
      vaccinePlaceholder: 'દા.ત. હેપબી, આઈપીવી, ટીડીએપ, વગેરે',
      vaccineDetails: 'રસી વિગતો',
      veccineDetailPlaceholder: 'દા.ત. ન્યુમોવાક્સ (મર્ક), એન્ટરિક્સ (ગિયાક્સમિસ્ટ ...',
      lotNumber: 'LOT નંબર',
      lotNu: 'e.g. AB0CA007A',
      notes: 'નોંધો'
    },
    addMedicalReport: {
      addMedicalReport: 'તબીબી અહેવાલ ઉમેરો',
      save: 'સાચવો',
      nameOfMedicalReport: 'મેડિકલ રિપોર્ટનું નામ',
      testTitle: 'TSH - દા.ત. ઉચ્ચ, ટી 4 - સામાન્ય',
      testTitlePlaceholder: 'દા.ત. છાતીનો એક્સ-રે, થાઇરોડ રક્ત પરીક્ષણ વગેરે.',
      prescribedBy: 'દ્વારા સૂચવેલ',
      testCenter: 'પરીક્ષણ કેન્દ્ર',
      addAttachment: 'જોડાણો ઉમેરો [ફાઇલ દીઠ મહત્તમ કદ 5MB]',
      uploadAttachment: 'જોડાણ અપલોડ કરો',
      notes: 'નોંધો'
    },
    addPatient: {
      addPatient: 'દર્દી ઉમેરો',
      save: 'સાચવો',
      mobileNumber: 'મોબાઇલ નંબર',
      firstName: 'પ્રથમ નામ',
      lastName: 'છેલ્લું નામ',
      dob: 'જન્મ તારીખ',
      gender: 'લિંગ',
      patientId: 'દર્દી ID (વૈકલ્પિક)'
    },
    consultationNotes: {
      consultationNotes: 'કન્સલ્ટેશન નોંધો',
      enabled: 'સક્ષમ',
      showing: 'દર્શાવે:',
      allConsultations: 'બધી પરામર્શ',
      filter: 'ફિલ્ટર કરો',
      introText: 'તમે આ દર્દી માટે હજી સુધી કોઈ orનલાઇન અથવા ક્લિનિક સલાહ-સૂચનો લ loggedગ ઇન કર્યા નથી.',
      logConsultation: 'લOગ કન્સલ્ટેશન',
      selectMonitoringPlanning: 'મોનીટરીંગ પ્લાનિંગ પસંદ કરો',
      allMonitoring: 'આ દર્દીને તમામ દેખરેખની યોજનાઓ સોંપવામાં આવી છે. તમારી એપ્લિકેશનમાં નવી દેખરેખ યોજના ઉમેરવા માટે વેબ પરથી એડમિન પોર્ટલની મુલાકાત લો.',
      clinicConsultation: 'ક્લિનિક કન્સલ્ટેશન',
      reasonForConsultation: 'સલાહ માટેનું કારણ',
      clinicSummary: 'ક્લિનિક સારાંશ',
      visibleToPatient: 'દર્દી માટે દૃશ્યમાન',
      viewAttachment: 'જોડાણ જુઓ',
      prescriptions: 'પ્રિસ્ક્રિપ્શનો',
      goals: 'લક્ષ્યો',
      attachments: 'જોડાણો',
      done: 'થઈ ગયું'
    },
    filterConsultationNotes: {
      consultationNotes: 'કન્સલ્ટેશન નોંધો',
      reset: 'ફરીથી સેટ કરો',
      filterByProvider: 'પ્રદાતા દ્વારા ફિલ્ટર કરો',
      filterByConsultationType: 'પરામર્શ પ્રકાર દ્વારા ફિલ્ટર કરો',
      filterByConsultationLocation: 'પરામર્શ સ્થાન દ્વારા ફિલ્ટર કરો',
      showConsultation: 'પરામર્શ બતાવો',
      all: 'બધા',
      for7Days: '7 દિવસો માટે',
      for30Days: '30 દિવસો માટે',
      byDate: 'તારીખ દ્વારા',
      apply: 'અરજી કરો',
      allConsultations: 'બધી પરામર્શ',
      clinicConsultations: 'ક્લિનિક પરામર્શ',
      videoConsultations: 'વિડિઓ સલાહ',
      patientQueationFollowup: 'પેશન્ટ ક્વોટેશન ફોલો અપ',
      remoteMonitoringFollowup: 'રિમોટ મોનિટરિંગ ફોલોઅપ',
      medicalReportReview: 'તબીબી અહેવાલ સમીક્ષા',
      from: 'થી',
      to: 'પ્રતિ'
    },
    appointmentList: {
      appointments: 'નિમણૂકો',
      new: 'નવું',
      confirmed: 'પુષ્ટિ આપી',
      confirm: 'ખાતરી કરો',
      reschedule: 'ફરીથી સેટ કરો',
      cancel: 'રદ કરો',
      rescheduleAppointment: 'ફરીથી નિયુક્તિ નિમણૂક',
      rescheduledDate: 'નિયત તારીખ',
      rescheduledTime: 'સુનિશ્ચિત સમય',
      noSlots: 'પસંદ કરેલી તારીખ માટે કોઈ સ્લોટ્સ ઉપલબ્ધ નથી',
      rescheduleNote: 'દર્દીને ફરીથી સુનિશ્ચિત નોંધ',
      submit: 'સબમિટ કરો',
      confirmAppointmtent: 'નિમણૂકની પુષ્ટિ કરો (વૈકલ્પિક)',
      selectAppointmtntType: 'એપોઇન્ટમેન્ટ ટાઈપ પસંદ કરો',
      clinicConsultation: 'ક્લિનિક કન્સલ્ટેશન',
      videoConsultation: 'વિડિઓ સલાહ'
    },
    appointmentFilter: {
      all: 'બધા',
      confirmed: 'પુષ્ટિ મળી',
      newOrReschedule: 'નવું અથવા ફરીથી સુનિશ્ચિત',
      cancelled: 'રદ કર્યું',
      concluded: 'નિષ્કર્ષ',
      video: 'વિડિઓ',
      clinic: 'ક્લિનિક',
      allPracticeLocation: 'બધા પ્રેક્ટિસ સ્થાન',
      allDepartment: 'બધા વિભાગ',
      allServices: 'બધી સેવાઓ',
      VideoCons: 'વિડિઓ કન્સલ્ટેશન (15) મિનિટ',
      appointmentFilter: 'નિમણૂક ફિલ્ટર',
      clinicSummary: 'ક્લિનિક સારાંશ',
      practiceLocation: 'પ્રેક્ટિસ સ્થાન',
      department: 'વિભાગ',
      healthcareProvider: 'આરોગ્યની સારસંભાળ સંબંધિત સેવાના પ્રદાતા',
      service: 'સેવા',
      appointmentStatus: 'નિમણૂક સ્થિતિ',
      clear: 'ચોખ્ખુ',
      apply: 'લાગુ કરો'
    },
    setClinicConsultation: {
      setClinicConsultation: 'ક્લિનિક કન્સલ્ટેશન સેટ કરો',
      done: 'થઈ ગયું',
      service: 'સેવા',
      practiceLocation: 'પ્રેક્ટિસ સ્થાન',
      showConsultationTimings: 'પરામર્શ સમય બતાવો',
      from: 'થી',
      to: 'પ્રતિ',
      patient: 'દર્દી',
      phonenumber: 'ફોન નંબર',
      reasonforAppointment: 'નિમણૂંક માટેનું કારણ',
      reasonPlaceholder: 'દર્દીની નિમણૂક નક્કી કરવા માટેનું એક કારણ દાખલ કરો'
    },
    consultationTimings: {
      monday: 'સોમવાર',
      tuesday: 'મંગળવારે',
      wednesday: 'બુધવાર',
      thursday: 'ગુરુવાર',
      friday: 'શુક્રવાર',
      saturday: 'શનિવાર',
      sunday: 'રવિવાર',
      timing: '* (IST = UTC + 05: 30) માં બતાવેલ સમય',
      consultationTimings: 'પરામર્શ સમય',
      done: 'થઈ ગયું',
      service: 'સેવા',
      practiceLocation: 'પ્રેક્ટિસ સ્થાન'
    },
    userProfile: {
      profile: "Profile",
      yourDetails: "Your Details",
      contactInfo: "Contact Info",
      manager: "Manager",
      phoneNumber: "Phone Number",
      about: "About",
      dashboard: "Dashboard",
      experience: "Experience",
      accomplishment: "Accomplishment",
      course: "Course",
      language: "Language",
      projects: "Projects",
      interests: "Inrerests",
      yourDashboard: "Your Dashboard",
      privateToYou: "Private to You",
      whoViewedYourProfile: "Who viewed your profile",
      postViews: "Post Views",
      searchAppearance: "Search Appearance",
      carrerInterests: "Career Interests",
      chooseTypeOpportunity: "Choose the types of opportunities you'd like to be connected with",
      salaryInsights: "Salary Insights",
      salaryInsightsNote: "See how salary compares to others in the community",
      editProfile: "Edit Profile",
      firstName: "First Name",
      lastName: "Last Name",
      headline: "Headline",
      countryRegion: "Country/Region",
      provinceState: "Province/State",
      cityDistrice: "City/District",
      save: "Save",
      takePhoto: "Take Photo...",
      chooseFromGallery: "Choose from Library",
      cancel: "Cancel",
      addExperience: "Add Experience",
      title: "Title",
      employmentType: "Employment Type",
      location: "Location",
      currentlyWorking: "I am currently working in this role",
      startDate: "Start Date",
      endDate: "End Date",
      description: "Description",
      Connections: "Connections"
    },
    betterMe: {
      requestFeedback: 'Request Feedback',
      sendFeedback: 'Send Feedback',
      feedbackRequests: 'Feedback Requests',
      history: 'History',
      betterMe: 'Better Me'
    },
    sendFeedback: {
      suggestedColleagues: 'Suggested Colleagues',
      findColleagues: 'Find Colleagues',
      sendFeedback: 'Send Feedback'
    },
    feedbackRequests: {
      answerRequest: 'Answer Request'
    },
    history: {
      received: 'Received',
      sent: 'Sent',
      loading: 'Loading'
    },
    takePart: {
      takePart: 'Take Part',
      whenDo: 'When do you prefer to do the Business workshop?',
      beingAble: 'Being able to generate and identify more ideas helps companies grow more quickly, stay relevant, and drive new trends.'
    },
    createTakePart: {
      createTakePart: 'Create Take Part',
      create: 'Create',
      chooseACardType: 'Choose a card type',
      tellUsYourWhy: 'Tell us your why',
      selectGroup: 'Select group to share card',
      what: 'WHAT?',
      why: 'WHY?',
      who: 'WHO?',
    },
    createCardReason: {
      createardReason: 'Why are you creating this card?',
      ansYes: 'Ans: Eg. Yes',
      ansNo: 'Ans: Eg. No',
      giveMoreDetails: 'Give More detail to this card',
      cardDetails: 'Card Details'
    },
    selectGroups: {
      chooseCardType: 'Choose Card Type',
      next: 'Next'
    },
    starMeUpChooseType: {
      sendAStar: 'Send A Star',
      selectedColleague: 'Selected Colleague',
      selectedGroups: 'Selected Groups/Colleague',
      placeHolder: 'Please tell us the reason you are recognizing your colleague',
      writeAComment: 'Write A Comment',
      send: 'Send'
    },
    starMeUpDashboard: {
      kudos: 'KUDOS',
      actEthecally: 'ACT ETHICALLY',
      teamPlayer: 'TEAM PLAYER',
      constantlyInnovate: 'CONSTANTLY INNOVATE',
      excellence_in_your_work: 'EXCELLENCE IN YOUR WORK',
      think_big: 'THINK BIG',
      have_fun: 'HAVE FUN',
      sendBy: 'send By',
      thisIsTextComment: 'This is text comment'
    },
    addGroup: {
      postToGroup: 'Post to group',
      selectColleague: 'Select Colleague',
      next: 'Next',
      startBy: 'Start by picking members for your groups.',
      emailPlaceholder: 'Type an email address'
    },
    createGroup: {
      create: 'Create',
      groupName: 'Group Name',
      financeLeadPlaceholder: 'Ex. Finance Leads',
      groupType: 'Group type and privacy',
      description: 'Description (Optional)',
      descriptionPlaceholder: 'Tell your member what your group is for eg. team planning, or organising a space mission.',
      groupMembers: 'Group Members'
    },
    events: {
      events: 'Events',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      previous: 'Previous',
      participents: 'Participents'
    },
    createEvent: {
      createEvent: 'CreateEvent',
      selectAvatar: 'Select Avatar',
      generalTeamMeeting: 'General Team Meeting',
      startDate: 'Start Date',
      startTime: 'Start Time',
      pickTime: 'Pick a time',
      endDate: 'End Date',
      endTime: 'End Time',
      location: 'Location',
      description: 'Description',
      guestCan: 'Guests can invite coworkers',
      cancle: 'CANCLE',
      create: 'CREATE',
      eventName: 'Event Name',
      addPhoto: 'ADD PHOTO'
    },
    eventDetails: {
      going: 'Going',
      mayBe: 'Maybe',
      invited: 'Invited',
      saySomething: 'Say Something...',
      photo: 'Photo',
      recentActivity: 'RECENT ACTIVITY',
      joinPod: 'Join Pod',
      attending: 'Attending :'
    },
    updateStatus: {
      updateStatus: 'Update Status',
      post: 'Post',
      photoVideo: 'Photo/Video/Screenshot',
      goLive: 'Go Live',
      checkIn: 'Check In',
      feelingActivity: 'Feeling/Activity/Sticker',
      tagFriends: 'Tag Friends',
      whatsOnYourMind: 'Whats on your mind?'
    },
    tagMembers: {
      tagMembers: 'Tag Members',
      done: 'DONE',
      searchGroups: 'Search Groups'
    },
    inviteColleague: {
      findPhone: 'Find phone contacts',
      pendingInvites: 'Pending Invites',
      invite: 'INVITE',
      inviteColleague: 'Invite Colleague',
      enterEmail: 'Type an email address'
    },
    peopleToFollow: {
      peopleToFollow: 'People To Follow'
    },
    home: {
      newsFeed: 'News Feed',
      writePost: 'Write Post'
    },
    postToGroup: {
      postToGroup: 'Post to a group',
      searchGroups: 'Search Groups',
      yourTopGroups: 'Your top groups',
      commonDiscussion: 'Common Discussion',
      socialDiscussion: 'Social Discussion',
      general: 'General',
      flowDiscussion: 'Flow Discussion',
      uiUx: 'UI/UX'
    }
  },

  /*
  .##.....##.####.##....##.########..####
  .##.....##..##..###...##.##.....##..##.
  .##.....##..##..####..##.##.....##..##.
  .#########..##..##.##.##.##.....##..##.
  .##.....##..##..##..####.##.....##..##.
  .##.....##..##..##...###.##.....##..##.
  .##.....##.####.##....##.########..####
  */

  hi: {
    authentication: {
      LogIn: 'लॉग इन करें',
      TermsConditions: 'नियम एवं शर्तें'
    },
    appCommon: {
      seeDetails: 'विवरण देखें',
      gender: "लिंग",
      healthBackground: "स्वास्थ्य पृष्ठभूमि",
      healthSmoker: "क्या आप धूम्रपान करते हैं?",
      healthHighBP: "क्या आपको कभी उच्च रक्तचाप का पता चला है?",
      healthDiabetes: "क्या आपको मधुमेह है?",
      yes: "हाँ",
      no: 'हाँ',
      notAnswred: "जवाब नहीं दिया",
      medication: "दवाएं",
      next: "आगे",
      comment: "टिप्पणी",
      send: "भेजो"
    },
    sidemenu: {
      myAssistant: "My Assistant",
      patient: "Patient",
      appointments: "Appointments",
      followup: "Follow-Up",
      consultationNotes: "Consultation Notes",
      blog: "Blog",
      followColleagues: "Follow Colleagues",
      inviteColleagues: "Invite Colleagues",
      chatColleagues: "Chat with Colleagues",
      events: "Events",
      betterMe: "Better Me",
      takePart: "Take Part",
      starmeUp: "StarMe Up",
      logout: "Log Out"
    },
    startScreen: {
      goodEvening: 'सुसंध्या',
      Pending: 'अपूर्ण',
      ToDo: 'करने के लिए',
      Started: 'शुरू कर दिया है',
      Done: 'किया हुआ',
      resend: 'पुनः भेजें',
      videocall: 'वीडियो कॉल'
    },
    patientDetails: {
      birthdayDate: 'जन्मदिन की तारीख',
      temperature: "तापमान",
      cough: "खांसी",
      completedOn: "पर पूर्ण",
      followupDay: "फॉलो-उप डे"
    },
    settings: {
      settings: "समायोजन",
      viewProfile: "अपनी प्रोफ़ाइल देखें",
      events: "आयोजन",
      batterMe: "बटेर मी",
      takePart: "टेक पार्ट",
      starmeUp: "स्टॉर्मी अप",
      logout: "लॉग आउट"
    },
    batterMe: {
      requestFeedback: "प्रतिक्रिया का अनुरोध करें",
      sendFeedback: "प्रतिक्रिया भेजें",
      feedbackRequests: "प्रतिक्रिया अनुरोध",
      history: "इतिहास",
      suggestedColleagues: "सुझाए गए सहयोगी",
      yourCompetencies: "आपकी योग्यताएँ",
      agility: "चपलता",
      orientation: "अभिविन्यास",
      relationships: "रिश्तों",
      creative: "रचनात्मक",
      ownership: "स्वामित्व",
      proactive: "सक्रिय",
      service: "सेवा",
      opener: "ओपनर",
      emotionalIntelligence: "भावनात्मक बुद्धि"
    },
    patientList: {
      patient: 'मरीज़',
      showing: 'दिखा रहे हैं:',
      activePatient: 'सक्रिय रोगी',
      cancel: 'रद्द करना',
      select: 'चुनते हैं',
      filter: 'फ़िल्टर'
    },
    patientDetailsScreen: {
      patientDetails: 'रोगी का विवरण',
      enabled: 'सक्रिय',
      health: 'स्वास्थ्य',
      profile: 'प्रोफ़ाइल',
      trackers: 'ट्रैकर्स',
      medical: 'मेडिकल',
      reports: 'रिपोर्ट',
      journals: 'पत्रिकाओं',
      consultation: 'परामर्श',
      notes: 'टिप्पणियाँ',
      patient: 'मरीज़',
      payments: 'भुगतान'
    },
    healthProfile: {
      healthProfile: 'स्वास्थ्य प्रोफ़ाइल',
      profile: 'प्रोफ़ाइल',
      trackers: 'ट्रैकर्स',
      reports: 'रिपोर्ट',
      enabled: 'सक्रिय',
      healthConditions: 'स्वास्थ्य की स्थिति',
      medications: 'दवाएं',
      allergies: 'एलर्जी',
      socialHistory: 'सामाजिक इतिहास',
      familyMedicalHistory: 'परिवार के मेडिकल इतिहास',
      contraindications: 'मतभेद',
      hospitalizations: 'अस्पताल में भर्ती',
      surgeryProcedure: 'सर्जरी / प्रक्रिया',
      vaccinations: 'टीकाकरण',
      bloodPressure: 'रक्तचाप',
      bloodSuger: 'खून में शक्कर',
      cholesterol: 'कोलेस्ट्रॉल',
      exercise: 'व्यायाम',
      food: 'खाना',
      height: 'ऊंचाई',
      jointStiffness: 'जोड़ो का अकड़ जाना',
      oxygenLevel: 'ऑक्सीजन स्तर',
      pain: 'दर्द',
      pulse: 'नाड़ी',
      respiratoryRates: 'श्वसन दर',
      sleep: 'नींद',
      temperature: 'तापमान',
      waistMeasurement: 'कमर का नाप',
      weight: 'वजन',
      noData: 'कोई आकड़ा उपलब्ध नहीं है',
      updateTracker: 'अद्यतन ट्रैक',
      noMedicle: 'इस रोगियों की कोई मेडिकल रिपोर्ट अभी तक अपलोड नहीं की गई है।',
      addNew: 'नया जोड़ें'
    },
    healthConditionList: {
      healthCondition: 'स्वास्थ्य की स्थिति',
      showing: 'दिखा रहे हैं:',
      all: 'सब',
      ongoing: 'चल रही है',
      past: 'अतीत',
      VitaminB12Deficiency: 'विटामिन बी 12 की कमी',
      type1Diabetese: 'टाइप 1 डायबिटीज (डीएम)',
      completed: 'पूरा कर लिया है'
    },
    addHealthCondition: {
      addHealthCondition: 'स्वास्थ्य स्थिति जोड़ें',
      save: 'सहेजें',
      nameOfCondition: 'दशा का नाम',
      nameOfConditionPlaceholder: 'जैसे उच्च रक्तचाप, प्रकार || मधुमेह',
      firstDiagnosedOn: 'पहले निदान किया गया',
      status: 'स्थिति',
      ongoing: 'चल रही है',
      medicationTaken: 'दवा लिया',
      addMedication: 'दवा जोड़ें',
      treatedBy: 'द्वारा इलाज',
      drName: 'डॉक्टर का नाम',
      notes: 'टिप्पणियाँ'
    },
    medicationsList: {
      medications: 'दवाएं',
      showing: 'दिखा रहे हैं:',
      allMedications: 'सभी दवाएं',
      ongoingMedications: 'चल रही दवाएं',
      pastMedications: 'विगत दवाएं',
    },
    addMedicationScreen: {
      addMedication: 'दवा जोड़ें',
      save: 'सहेजें',
      medicationName: 'दवा का नाम',
      medicationPlaceholder: 'दवा का नाम दर्ज करें',
      formOfMedicine: 'चिकित्सा का रूप',
      methodOfIntake: 'सेवन की विधि',
      dosage: 'मात्रा बनाने की विधि',
      quality: 'गुणवत्ता',
      frequencyOfIntake: 'सेवन की आवृत्ति',
      when: 'कब',
      addAnotherDosage: 'जोड़ें अन्य खुराक',
      addAnotherDosagePlaceholder: 'अपनी दवा के सेवन से संबंधित कोई भी जानकारी दर्ज करें',
      duration: 'समयांतराल',
      beforeMeals: 'खाने से पहले',
      withMeals: 'खाने के साथ',
      afterMeals: 'भोजन के बाद',
      atBedtime: 'सोने के समय',
      morningAndEveningAfterMeals: 'सुबह और शाम भोजन के बाद',
      morningAndAfternoonAfterMeals: 'भोजन के बाद सुबह और दोपहर',
      afternoonAndEveningAfterMeals: 'भोजन के बाद दोपहर और शाम',
      morningAndEveningBeforeMeals: 'सुबह और शाम भोजन से पहले',
      morningAndAfternoonBeforeMeals: 'भोजन से पहले सुबह और दोपहर',
      afternoonAndEveningBeforeMeals: 'दोपहर और शाम भोजन से पहले',
      morningAfterMeals: 'भोजन के बाद सुबह',
      morningBeforeMeals: 'भोजन से पहले सुबह',
      afternoonAfterMeals: 'भोजन के बाद दोपहर',
      afternoonBeforeMeals: 'भोजन से पहले दोपहर',
      eveningBeforeMeans: 'मतलब से पहले शाम',
      morningWithMeals: 'भोजन के साथ सुबह',
      afternoonWithMeals: 'दोपहर को भोजन के साथ',
      eveningWithMeals: 'भोजन के साथ शाम',
      oneHourAfterMeals: 'भोजन के एक घंटे बाद',
      oneHourBeforeMeals: 'भोजन से एक घंटा पहले',
      twoHourAfterMeals: 'भोजन के दो घंटे बाद',
      halfHourBeforeMeals: 'भोजन से आधा घंटा पहले'
    },
    allergiesList: {
      allergies: 'एलर्जी',
      latexAllergy: 'लेटेक्स एलर्जी',
      cough: 'खांसी'
    },
    addOptionsHealthProfile: {
      occupation: 'व्यवसाय',
      education: 'शिक्षा',
      educationYear: 'शिक्षा वर्ष',
      birthPlace: 'जन्म स्थान',
      maritalStatus: 'वैवाहिक स्थिति',
      children: 'बच्चे',
      religion: 'धर्म',
      generalDiet: 'सामान्य आहार',
      sexualOrientation: 'यौन अभिविन्यास',
      smoking: 'धूम्रपान',
      alcoholConsumption: 'शराब की खपत',
      substanceUse: 'पदार्थ का उपयोग',
      exercise: 'व्यायाम',
      stressFactor: 'तनाव कारक',
      languageSpoken: 'बोली जाने वाली भाषा',
      secondaryLanguageSpoken: 'माध्यमिक भाषा स्पोकेन',
      addNew: 'नया जोड़ें',
      newTask: 'नया कार्य',
      notifications: 'सूचनाएं',
      allTasks: 'सभी कार्य',
      showing: 'दिखा रहे हैं:',
      hcIntro: 'इस रोगी के लिए सभी ज्ञात स्वास्थ्य स्थितियाँ जोड़ें।',
      mediIntro: 'इस फ़िल्टर से मेल खाने वाली कोई दवा नहीं हैं।',
      allergyIntro: 'इस रोगी की सभी ज्ञात एलर्जी जोड़ें।',
      scIntro: 'ज्ञात सामाजिक इतिहास विवरण अपडेट करें।',
      familyIntro: 'मरीज के परिवार के मेडिकल इतिहास को अपडेट करें।',
      conIntro: 'इस रोगी के लिए सभी ज्ञात contraindications जोड़ें।',
      hospiIntro: 'इस रोगी के लिए पिछले अस्पताल में भर्ती होने का इतिहास जोड़ें।',
      surIntro: 'यदि कोई हो, तो सर्जरी और प्रत्यारोपण का विवरण जोड़ें।',
      vaccineIntro: 'इस रोगी द्वारा लिए गए सभी ज्ञात टीकाकरणों को जोड़ें।'
    },
    familyMedicalHistoryList: {
      familyMedicalHistory: 'परिवार के मेडिकल इतिहास'
    },
    addFamilyMedicalHistory: {
      addFamilyMedicalHistory: 'परिवार चिकित्सा इतिहास जोड़ें',
      save: 'सहेजें',
      relationship: 'संबंध',
      notePlaceholder: 'जैसे उच्च रक्तचाप और हृदय रोग का इतिहास है। 8 साल पहले उनकी ओपन हार्ट सर्जरी हुई थी।',
      mother: 'मां',
      father: 'पिता जी',
      siblings: 'एक माँ की संताने',
      grandPatents: 'ग्रैंड पेटेंट',
      children: 'बच्चे',
      others: 'अन्य',
      selectOne: 'एक चुनो...'
    },
    contraindicationList: {
      contraindications: 'मतभेद'
    },
    addContraindication: {
      addContraindication: 'कंट्राडिक्शन जोड़ें',
      save: 'सहेजें',
      description: 'विवरण',
      descPlaceholder: 'जैसे मुझे हाई बीपी के कारण साइनसाइटिस के लिए डिकॉन्गेस्टेंट लेने के खिलाफ सलाह दी गई थी'
    },
    hospitalizationList: {
      hospitalization: 'अस्पताल में भर्ती',
      treatedBy: 'द्वारा इलाज:',
      for: 'के लिये:',
      all: 'सब',
      ongoing: 'चल रही है',
      past: 'अतीत'
    },
    AddHospitalization: {
      addHospitalization: 'अस्पताल में भर्ती जोड़ें',
      save: 'सहेजें',
      admissionDate: 'प्रवेश तिथि',
      startDate: 'आरंभ करने की तिथि',
      dischargeDate: 'कार्यमुक्ति दिवस',
      endDate: 'अंतिम तिथि',
      providerName: 'प्रदाता का नाम',
      hospitalName: 'अस्पताल का नाम',
      respiratoryIllness: 'साँस की बीमारी',
      addAttchment: 'अनुलग्नक जोड़ें [प्रति फ़ाइल अधिकतम आकार 5 एमबी]'
    },
    surgeryList: {
      headerName: 'सर्जरी / प्रक्रिया',
      conductedOn: 'पर संचालित:',
      operatedBy: 'द्वारा संचालित:'
    },
    addSurguryProcedure: {
      headerName: 'सर्जरी / प्रक्रिया जोड़ें',
      save: 'सहेजें',
      name: 'नाम',
      allergyPlaceholder: 'जैसे फिटिंग पेसमेकर, किडनी की पथरी निकालने ...',
      conductedOn: 'पर संचालित',
      implants: 'प्रत्यारोपण / सहायता उपकरण',
      implantsPlaceholder: 'जैसे पेसमेकर, स्टेंट, घुटने का जोड़, आदि',
      operatedBy: 'द्वारा संचालित',
      operatedByPlaceholder: 'जैसे ऑर्थो अस्पताल में डॉ। गोपन, आदि',
      notes: 'टिप्पणियाँ'
    },
    vaccinationList: {
      vaccinationList: 'टीकाकरण सूची',
      vaccinatedOn: 'पर टीका लगाया गया:',
      vaccineName: 'वैक्सीन का नाम:'
    },
    addVaccinationList: {
      addVaccination: 'टीकाकरण जोड़ें',
      save: 'सहेजें',
      vaccineTakenFor: 'के लिए लिया गया टीका',
      vaccinePlaceholder: 'जैसे होपिट्स बी, पोलियो, टेटनस, आदि',
      takenOn: 'पर लिया गया',
      vaccineName: 'वैक्सीन का नाम',
      vaccinePlaceholder: 'जैसे HepB, IPV, Tdap, आदि',
      vaccineDetails: 'वैक्सीन का विवरण',
      veccineDetailPlaceholder: 'जैसे न्यूमोवैक्स (मर्क), एंटरिक्स (जियाक्सोमिट ...',
      lotNumber: 'बहुत संख्या',
      lotNu: 'e.g. AB0CA007A',
      notes: 'टिप्पणियाँ'
    },
    addMedicalReport: {
      addMedicalReport: 'मेडिकल रिपोर्ट जोड़ें',
      save: 'सहेजें',
      nameOfMedicalReport: 'मेडिकल रिपोर्ट का नाम',
      testTitle: 'टीएसएच - जैसे उच्च, टी 4 - सामान्य',
      testTitlePlaceholder: 'जैसे छाती का एक्स-रे, थायरॉड रक्त परीक्षण आदि।',
      prescribedBy: 'द्वारा निर्धारित',
      testCenter: 'परीक्षण केंद्र',
      addAttachment: 'अनुलग्नक जोड़ें [प्रति फ़ाइल अधिकतम आकार 5 एमबी]',
      uploadAttachment: 'अटैचमेंट अपलोड करें',
      notes: 'टिप्पणियाँ'
    },
    addPatient: {
      addPatient: 'रोगी जोड़ें',
      save: 'सहेजें',
      mobileNumber: 'मोबाइल नंबर',
      firstName: 'पहला नाम',
      lastName: 'अंतिम नाम',
      dob: 'जन्म की तारीख',
      gender: 'लिंग',
      patientId: 'रोगी आईडी (वैकल्पिक)'
    },
    consultationNotes: {
      consultationNotes: 'परामर्श नोट्स',
      enabled: 'सक्रिय',
      showing: 'दिखा रहे हैं:',
      allConsultations: 'सभी परामर्श',
      filter: 'फ़िल्टर',
      introText: 'आपने इस रोगी के लिए अभी तक कोई ऑनलाइन या क्लिनिक परामर्श नहीं लिया है।',
      logConsultation: 'लॉग परामर्श',
      selectMonitoringPlanning: 'निगरानी योजना का चयन करें',
      allMonitoring: 'सभी निगरानी योजनाओं को इस रोगी को सौंपा गया है। अपने ऐप में एक नया मॉनिटरिंग प्लान जोड़ने के लिए वेब से एडमिन पोर्टल पर जाएं।',
      clinicConsultation: 'क्लिनिक परामर्श',
      reasonForConsultation: 'परामर्श का कारण',
      clinicSummary: 'क्लिनिक सारांश',
      visibleToPatient: 'रोगी के लिए दृश्यमान',
      viewAttachment: 'अनुलग्नक देखें',
      prescriptions: 'नुस्खे',
      goals: 'लक्ष्य',
      attachments: 'संलग्नक',
      done: 'किया हुआ'
    },
    filterConsultationNotes: {
      consultationNotes: 'परामर्श नोट्स',
      reset: 'रीसेट',
      filterByProvider: 'प्रदाता द्वारा फ़िल्टर करें',
      filterByConsultationType: 'परामर्श प्रकार से फ़िल्टर करें',
      filterByConsultationLocation: 'परामर्श स्थान से फ़िल्टर करें',
      showConsultation: 'परामर्श दिखाएं',
      all: 'सब',
      for7Days: '7 दिनों के लिए',
      for30Days: '30 दिनों के लिए',
      byDate: 'तिथि के अनुसार',
      apply: 'लागू',
      allConsultations: 'सभी परामर्श',
      clinicConsultations: 'क्लिनिक परामर्श',
      videoConsultations: 'वीडियो परामर्श',
      patientQueationFollowup: 'रोगी उद्धरण का पालन करें',
      remoteMonitoringFollowup: 'रिमोट मॉनिटरिंग फॉलोअप',
      medicalReportReview: 'मेडिकल रिपोर्ट की समीक्षा',
      from: 'से',
      to: 'सेवा'
    },
    appointmentList: {
      appointments: 'नियुक्ति',
      new: 'नया',
      confirmed: 'की पुष्टि',
      confirm: 'पुष्टि करें',
      reschedule: 'पुनर्निर्धारित',
      cancel: 'रद्द करना',
      rescheduleAppointment: 'मिलने के समय को दोबारा अनुसूचित करें',
      rescheduledDate: 'पुनर्निर्धारित तिथि',
      rescheduledTime: 'पुनर्निर्धारित समय',
      noSlots: 'चुनी गई तारीख के लिए कोई स्लॉट उपलब्ध नहीं है',
      rescheduleNote: 'रोगी को पुनर्निर्धारित नोट',
      submit: 'प्रस्तुत',
      confirmAppointmtent: 'नियुक्ति की पुष्टि करें (वैकल्पिक)',
      selectAppointmtntType: 'Appointmtnt प्रकार का चयन करें',
      clinicConsultation: 'क्लिनिक परामर्श',
      videoConsultation: 'वीडियो परामर्श'
    },
    appointmentFilter: {
      all: 'सब',
      confirmed: 'की पुष्टि',
      newOrReschedule: 'नया या पुनर्निर्धारित',
      cancelled: 'रद्द',
      concluded: 'निष्कर्ष निकाला',
      video: 'वीडियो',
      clinic: 'क्लिनिक',
      allPracticeLocation: 'सभी अभ्यास स्थान',
      allDepartment: 'सभी विभाग',
      allServices: 'सभी सेवाएँ',
      VideoCons: 'वीडियो परामर्श (15) मिनट',
      appointmentFilter: 'अपॉइंटमेंट फ़िल्टर',
      clinicSummary: 'क्लिनिक सारांश',
      practiceLocation: 'स्थान का अभ्यास करें',
      department: 'विभाग',
      healthcareProvider: 'स्वास्थ्य सेवाएं देने वाला',
      service: 'सर्विस',
      appointmentStatus: 'नियुक्ति की स्थिति',
      clear: 'स्पष्ट',
      apply: 'लागू'
    },
    setClinicConsultation: {
      setClinicConsultation: 'क्लिनिक परामर्श सेट करें',
      done: 'किया हुआ',
      service: 'सर्विस',
      practiceLocation: 'स्थान का अभ्यास करें',
      showConsultationTimings: 'परामर्श समय दिखाएँ',
      from: 'से',
      to: 'सेवा',
      patient: 'मरीज़',
      phonenumber: 'फ़ोन नंबर',
      reasonforAppointment: 'नियुक्ति का कारण',
      reasonPlaceholder: 'रोगी की नियुक्ति निर्धारित करने के लिए एक कारण दर्ज करें'
    },
    consultationTimings: {
      monday: 'सोमवार',
      tuesday: 'मंगलवार',
      wednesday: 'बुधवार',
      thursday: 'गुरूवार',
      friday: 'शुक्रवार',
      saturday: 'शनिवार',
      sunday: 'रविवार',
      timing: '* समय दिखाया गया है (IST = UTC + 05: 30)',
      consultationTimings: 'परामर्श समय',
      done: 'किया हुआ',
      service: 'सर्विस',
      practiceLocation: 'स्थान का अभ्यास करें'
    },
    userProfile: {
      profile: "Profile",
      yourDetails: "Your Details",
      contactInfo: "Contact Info",
      manager: "Manager",
      phoneNumber: "Phone Number",
      about: "About",
      dashboard: "Dashboard",
      experience: "Experience",
      accomplishment: "Accomplishment",
      course: "Course",
      language: "Language",
      projects: "Projects",
      interests: "Inrerests",
      yourDashboard: "Your Dashboard",
      privateToYou: "Private to You",
      whoViewedYourProfile: "Who viewed your profile",
      postViews: "Post Views",
      searchAppearance: "Search Appearance",
      carrerInterests: "Career Interests",
      chooseTypeOpportunity: "Choose the types of opportunities you'd like to be connected with",
      salaryInsights: "Salary Insights",
      salaryInsightsNote: "See how salary compares to others in the community",
      editProfile: "Edit Profile",
      firstName: "First Name",
      lastName: "Last Name",
      headline: "Headline",
      countryRegion: "Country/Region",
      provinceState: "Province/State",
      cityDistrice: "City/District",
      save: "Save",
      takePhoto: "Take Photo...",
      chooseFromGallery: "Choose from Library",
      cancel: "Cancel",
      addExperience: "Add Experience",
      title: "Title",
      employmentType: "Employment Type",
      location: "Location",
      currentlyWorking: "I am currently working in this role",
      startDate: "Start Date",
      endDate: "End Date",
      description: "Description",
      Connections: "Connections"
    },
    betterMe: {
      requestFeedback: 'Request Feedback',
      sendFeedback: 'Send Feedback',
      feedbackRequests: 'Feedback Requests',
      history: 'History',
      betterMe: 'Better Me'
    },
    sendFeedback: {
      suggestedColleagues: 'Suggested Colleagues',
      findColleagues: 'Find Colleagues',
      sendFeedback: 'Send Feedback'
    },
    feedbackRequests: {
      answerRequest: 'Answer Request'
    },
    history: {
      received: 'Received',
      sent: 'Sent',
      loading: 'Loading'
    },
    takePart: {
      takePart: 'Take Part',
      whenDo: 'When do you prefer to do the Business workshop?',
      beingAble: 'Being able to generate and identify more ideas helps companies grow more quickly, stay relevant, and drive new trends.'
    },
    createTakePart: {
      createTakePart: 'Create Take Part',
      create: 'Create',
      chooseACardType: 'Choose a card type',
      tellUsYourWhy: 'Tell us your why',
      selectGroup: 'Select group to share card',
      what: 'WHAT?',
      why: 'WHY?',
      who: 'WHO?',
    },
    createCardReason: {
      createardReason: 'Why are you creating this card?',
      ansYes: 'Ans: Eg. Yes',
      ansNo: 'Ans: Eg. No',
      giveMoreDetails: 'Give More detail to this card',
      cardDetails: 'Card Details'
    },
    selectGroups: {
      chooseCardType: 'Choose Card Type',
      next: 'Next'
    },
    starMeUpChooseType: {
      sendAStar: 'Send A Star',
      selectedColleague: 'Selected Colleague',
      selectedGroups: 'Selected Groups/Colleague',
      placeHolder: 'Please tell us the reason you are recognizing your colleague',
      writeAComment: 'Write A Comment',
      send: 'Send'
    },
    starMeUpDashboard: {
      kudos: 'KUDOS',
      actEthecally: 'ACT ETHICALLY',
      teamPlayer: 'TEAM PLAYER',
      constantlyInnovate: 'CONSTANTLY INNOVATE',
      excellence_in_your_work: 'EXCELLENCE IN YOUR WORK',
      think_big: 'THINK BIG',
      have_fun: 'HAVE FUN',
      sendBy: 'send By',
      thisIsTextComment: 'This is text comment'
    },
    addGroup: {
      postToGroup: 'Post to group',
      selectColleague: 'Select Colleague',
      next: 'Next',
      startBy: 'Start by picking members for your groups.',
      emailPlaceholder: 'Type an email address'
    },
    createGroup: {
      create: 'Create',
      groupName: 'Group Name',
      financeLeadPlaceholder: 'Ex. Finance Leads',
      groupType: 'Group type and privacy',
      description: 'Description (Optional)',
      descriptionPlaceholder: 'Tell your member what your group is for eg. team planning, or organising a space mission.',
      groupMembers: 'Group Members'
    },
    events: {
      events: 'Events',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      previous: 'Previous',
      participents: 'Participents'
    },
    createEvent: {
      createEvent: 'CreateEvent',
      selectAvatar: 'Select Avatar',
      generalTeamMeeting: 'General Team Meeting',
      startDate: 'Start Date',
      startTime: 'Start Time',
      pickTime: 'Pick a time',
      endDate: 'End Date',
      endTime: 'End Time',
      location: 'Location',
      description: 'Description',
      guestCan: 'Guests can invite coworkers',
      cancle: 'CANCLE',
      create: 'CREATE',
      eventName: 'Event Name',
      addPhoto: 'ADD PHOTO'
    },
    eventDetails: {
      going: 'Going',
      mayBe: 'Maybe',
      invited: 'Invited',
      saySomething: 'Say Something...',
      photo: 'Photo',
      recentActivity: 'RECENT ACTIVITY',
      joinPod: 'Join Pod',
      attending: 'Attending :'
    },
    updateStatus: {
      updateStatus: 'Update Status',
      post: 'Post',
      photoVideo: 'Photo/Video/Screenshot',
      goLive: 'Go Live',
      checkIn: 'Check In',
      feelingActivity: 'Feeling/Activity/Sticker',
      tagFriends: 'Tag Friends',
      whatsOnYourMind: 'Whats on your mind?'
    },
    tagMembers: {
      tagMembers: 'Tag Members',
      done: 'DONE',
      searchGroups: 'Search Groups'
    },
    inviteColleague: {
      findPhone: 'Find phone contacts',
      pendingInvites: 'Pending Invites',
      invite: 'INVITE',
      inviteColleague: 'Invite Colleague',
      enterEmail: 'Type an email address'
    },
    peopleToFollow: {
      peopleToFollow: 'People To Follow'
    },
    home: {
      newsFeed: 'News Feed',
      writePost: 'Write Post'
    },
    postToGroup: {
      postToGroup: 'Post to a group',
      searchGroups: 'Search Groups',
      yourTopGroups: 'Your top groups',
      commonDiscussion: 'Common Discussion',
      socialDiscussion: 'Social Discussion',
      general: 'General',
      flowDiscussion: 'Flow Discussion',
      uiUx: 'UI/UX'
    }
  },

  /*
  ..######..##.....##.####.##....##.########..######..########
  .##....##.##.....##..##..###...##.##.......##....##.##......
  .##.......##.....##..##..####..##.##.......##.......##......
  .##.......#########..##..##.##.##.######....######..######..
  .##.......##.....##..##..##..####.##.............##.##......
  .##....##.##.....##..##..##...###.##.......##....##.##......
  ..######..##.....##.####.##....##.########..######..########
  */

  zh: {
    authentication: {
      LogIn: '登录',
      TermsConditions: '条款及细则'
    },
    appCommon: {
      seeDetails: '查看详细信息',
      gender: "性别",
      healthBackground: "健康背景",
      healthSmoker: "你是吸烟者吗？",
      healthHighBP: "您曾经被诊断出患有高血压吗？",
      healthDiabetes: "你有糖尿病吗？",
      yes: "是",
      no: '没有',
      notAnswred: "没有回答",
      medication: "药物",
      next: "下一个",
      comment: "评论",
      send: "发送"
    },
    sidemenu: {
      myAssistant: "我的助手",
      patient: "患者",
      appointments: "预约时间",
      followup: "跟进",
      consultationNotes: "咨询须知",
      blog: "博客",
      followColleagues: "关注同事",
      inviteColleagues: "邀请同事",
      chatColleagues: "与同事聊天",
      events: "大事记",
      betterMe: "更好的我",
      takePart: "参与",
      starmeUp: "给我加星",
      logout: "登出"
    },
    startScreen: {
      goodEvening: '晚上好',
      Pending: '待定',
      ToDo: '去做',
      Started: '已开始',
      Done: '完成了',
      resend: '重发',
      videocall: '视频电话'
    },
    patientDetails: {
      birthdayDate: '生日日期',
      temperature: "温度",
      cough: "咳嗽",
      completedOn: "完成于",
      followupDay: "后续日"
    },
    settings: {
      settings: "设定值",
      viewProfile: "查看你的个人资料",
      events: "大事记",
      batterMe: "更好的我",
      takePart: "参与",
      starmeUp: "给我加星",
      logout: "登出"
    },
    batterMe: {
      requestFeedback: "要求反馈",
      sendFeedback: "发送反馈",
      feedbackRequests: "回应要求",
      history: "历史",
      suggestedColleagues: "建议合作伙伴",
      yourCompetencies: "您的资格",
      agility: "敏捷",
      orientation: "方向",
      relationships: "人际关系",
      creative: "创意性",
      ownership: "所有权",
      proactive: "活性",
      service: "服务",
      opener: "开瓶器",
      emotionalIntelligence: "情商"
    },
    patientList: {
      patient: '患者',
      showing: '显示：',
      activePatient: '活跃患者',
      cancel: '取消',
      select: '选择',
      filter: '过滤'
    },
    patientDetailsScreen: {
      patientDetails: '患者详细资料',
      enabled: '已启用',
      health: '健康',
      profile: '个人资料',
      trackers: '追踪器',
      medical: '医疗类',
      reports: '报告书',
      journals: '期刊',
      consultation: '咨询服务',
      notes: '笔记',
      patient: '患者',
      payments: '付款方式'
    },
    healthProfile: {
      healthProfile: '健康状况',
      profile: '个人资料',
      trackers: '追踪器',
      reports: '报告书',
      enabled: '已启用',
      healthConditions: '健康状况',
      medications: '药物治疗',
      allergies: '过敏症',
      socialHistory: '社会史',
      familyMedicalHistory: '家庭病史',
      contraindications: '禁忌症',
      hospitalizations: '住院治疗',
      surgeryProcedure: '手术/程序',
      vaccinations: '预防接种',
      bloodPressure: '血压',
      bloodSuger: '血糖',
      cholesterol: '胆固醇',
      exercise: '行使',
      food: '餐饮',
      height: '高度',
      jointStiffness: '关节刚度',
      oxygenLevel: '氧气水平',
      pain: '痛',
      pulse: '脉冲',
      respiratoryRates: '呼吸频率',
      sleep: '睡觉',
      temperature: '温度',
      waistMeasurement: '腰围',
      weight: '重量',
      noData: '没有数据',
      updateTracker: '更新跟踪器',
      noMedicle: '尚未上载有关该患者的医学报告。',
      addNew: '添新'
    },
    healthConditionList: {
      healthCondition: '健康状况',
      showing: '显示：',
      all: '所有',
      ongoing: '进行中',
      past: '过去',
      VitaminB12Deficiency: '维生素B12缺乏症',
      type1Diabetese: '1型糖尿病（DM）',
      completed: '已完成'
    },
    addHealthCondition: {
      addHealthCondition: '添加健康状况',
      save: '保存',
      nameOfCondition: '条件名称',
      nameOfConditionPlaceholder: '例如 高血压，类型|| 糖尿病',
      firstDiagnosedOn: '首次诊断',
      status: '状态',
      ongoing: '进行中',
      medicationTaken: '服药',
      addMedication: '添加药物',
      treatedBy: '处理者',
      drName: '医生姓名',
      notes: '笔记'
    },
    medicationsList: {
      medications: '药物治疗',
      showing: '显示：',
      allMedications: '所有药物',
      ongoingMedications: '持续用药',
      pastMedications: '过去的药物',
    },
    addMedicationScreen: {
      addMedication: '添加药物',
      save: '保存',
      medicationName: '药物名称',
      medicationPlaceholder: '输入药物名称',
      formOfMedicine: '药物形式',
      methodOfIntake: '摄入方式',
      dosage: '剂量',
      quality: '质量',
      frequencyOfIntake: '摄入频率',
      when: '什么时候',
      addAnotherDosage: '添加其他剂量',
      addAnotherDosagePlaceholder: '输入与您的药物摄入量有关的任何信息',
      duration: '持续时间',
      beforeMeals: '吃饭前',
      withMeals: '含餐',
      afterMeals: '吃完以后',
      atBedtime: '就寝时间',
      morningAndEveningAfterMeals: '饭后早晚',
      morningAndAfternoonAfterMeals: '饭后早上和下午',
      afternoonAndEveningAfterMeals: '饭后下午和晚上',
      morningAndEveningBeforeMeals: '饭前早晚',
      morningAndAfternoonBeforeMeals: '饭前早晚',
      afternoonAndEveningBeforeMeals: '饭后下午和晚上',
      morningAfterMeals: '饭后早上',
      morningBeforeMeals: '饭前早晨',
      afternoonAfterMeals: '饭后下午',
      afternoonBeforeMeals: '饭前下午',
      eveningBeforeMeans: '傍晚之前',
      morningWithMeals: '早上吃饭',
      afternoonWithMeals: '下午用餐',
      eveningWithMeals: '晚饭',
      oneHourAfterMeals: '饭后一小时',
      oneHourBeforeMeals: '饭前一小时',
      twoHourAfterMeals: '饭后两个小时',
      halfHourBeforeMeals: '饭前半小时'
    },
    allergiesList: {
      allergies: '过敏症',
      latexAllergy: '乳胶过敏',
      cough: '咳嗽'
    },
    addOptionsHealthProfile: {
      occupation: '占用',
      education: '教育',
      educationYear: '教育年',
      birthPlace: '出生地',
      maritalStatus: '婚姻状况',
      children: '小孩儿',
      religion: '宗教',
      generalDiet: '一般饮食',
      sexualOrientation: '性取向',
      smoking: '抽烟',
      alcoholConsumption: '酒精消耗',
      substanceUse: '物质使用',
      exercise: '行使',
      stressFactor: '压力因素',
      languageSpoken: '说的语言',
      secondaryLanguageSpoken: '第二语言口语',
      addNew: '添新',
      newTask: '新任务',
      notifications: '通知事项',
      allTasks: '所有任务',
      showing: '显示：',
      hcIntro: '添加该患者的所有已知健康状况。',
      mediIntro: '没有与此过滤器匹配的药物。',
      allergyIntro: '添加此患者的所有已知过敏。',
      scIntro: '更新已知的社会历史记录详细信息。',
      familyIntro: '更新患者的家庭病史。',
      conIntro: '添加该患者的所有已知禁忌症。',
      hospiIntro: '添加该患者过去的住院记录。',
      surIntro: '添加手术和植入物的详细信息（如果有）。',
      vaccineIntro: '添加该患者服用的所有已知疫苗。'
    },
    familyMedicalHistoryList: {
      familyMedicalHistory: '家庭病史'
    },
    addFamilyMedicalHistory: {
      addFamilyMedicalHistory: '添加家庭病史',
      save: '保存',
      relationship: '关系',
      notePlaceholder: '例如 有高血压和心脏病史。 他在8年前接受了心脏直视手术。',
      mother: '母亲',
      father: '父亲',
      siblings: '兄弟姐妹',
      grandPatents: '大专利',
      children: '小孩儿',
      others: '其他',
      selectOne: '选择一个...'
    },
    contraindicationList: {
      contraindications: '禁忌症'
    },
    addContraindication: {
      addContraindication: '添加禁忌',
      save: '保存',
      description: '描述',
      descPlaceholder: '例如 建议我不要因血压高而服用充血性鼻窦炎'
    },
    hospitalizationList: {
      hospitalization: '住院治疗',
      treatedBy: '处理者：',
      for: '对于：',
      all: '所有',
      ongoing: '进行中',
      past: '过去'
    },
    AddHospitalization: {
      addHospitalization: '添加住院',
      save: '保存',
      admissionDate: '入学日期',
      startDate: '开始日期',
      dischargeDate: '出院日期',
      endDate: '结束日期',
      providerName: '提供商名称',
      hospitalName: '医院名称',
      respiratoryIllness: '呼吸系统疾病',
      addAttchment: '添加附件[每个文件最大5MB]'
    },
    surgeryList: {
      headerName: '手术/程序',
      conductedOn: '进行：',
      operatedBy: '操作者：'
    },
    addSurguryProcedure: {
      headerName: '添加手术/程序',
      save: '保存',
      name: '名称',
      allergyPlaceholder: '例如 安装起搏器，去除肾结石...',
      conductedOn: '进行',
      implants: '植入物/支持设备',
      implantsPlaceholder: '例如 起搏器，支架，膝关节等',
      operatedBy: '由...经营',
      operatedByPlaceholder: '例如 Ortho医院的Gopan博士等',
      notes: '笔记'
    },
    vaccinationList: {
      vaccinationList: '疫苗接种清单',
      vaccinatedOn: '接种疫苗：',
      vaccineName: '疫苗名称：'
    },
    addVaccinationList: {
      addVaccination: '增加疫苗接种',
      save: '保存',
      vaccineTakenFor: '采取的疫苗',
      vaccinePlaceholder: '例如 Hopatits B，脊髓灰质炎，破伤风等',
      takenOn: '承担',
      vaccineName: '疫苗名称',
      vaccinePlaceholder: '例如 HebB，IPV，Tdap等',
      vaccineDetails: '疫苗详情',
      veccineDetailPlaceholder: '例如 Pneumovax（Merck），Enterix（GiaxoSmit ...',
      lotNumber: '批号',
      lotNu: 'e.g. AB0CA007A',
      notes: '笔记'
    },
    addMedicalReport: {
      addMedicalReport: '添加医疗报告',
      save: '保存',
      nameOfMedicalReport: '医疗报告名称',
      testTitle: 'TSH-例如 高，T4-正常',
      testTitlePlaceholder: '例如 胸部X光检查，甲状腺抽血检查等',
      prescribedBy: '订明者',
      testCenter: '测试中心',
      addAttachment: '添加附件[每个文件最大5MB]',
      uploadAttachment: '上传附件',
      notes: '笔记'
    },
    addPatient: {
      addPatient: '添加患者',
      save: '保存',
      mobileNumber: '手机号码',
      firstName: '名字',
      lastName: '姓',
      dob: '出生日期',
      gender: '性别',
      patientId: '患者ID（可选）'
    },
    consultationNotes: {
      consultationNotes: '咨询须知',
      enabled: '已启用',
      showing: '显示：',
      allConsultations: '所有咨询',
      filter: '过滤',
      introText: '您尚未为此患者记录任何在线或诊所咨询。',
      logConsultation: '日志咨询',
      selectMonitoringPlanning: '选择监控计划',
      allMonitoring: '已将所有监测计划分配给该患者。 要将新的监控计划添加到您的appm，请从网络访问管理门户。',
      clinicConsultation: '诊所咨询',
      reasonForConsultation: '咨询理由',
      clinicSummary: '临床总结',
      visibleToPatient: '对患者可见',
      viewAttachment: '查看附件',
      prescriptions: '处方药',
      goals: '目标',
      attachments: '附件',
      done: '完成了'
    },
    filterConsultationNotes: {
      consultationNotes: '咨询须知',
      reset: '重启',
      filterByProvider: '按提供者筛选',
      filterByConsultationType: '按咨询类型过滤',
      filterByConsultationLocation: '按咨询地点筛选',
      showConsultation: '显示咨询',
      all: '所有',
      for7Days: '7天',
      for30Days: '30天',
      byDate: '按日期',
      apply: '应用',
      allConsultations: '所有咨询',
      clinicConsultations: '诊所咨询',
      videoConsultations: '视频咨询',
      patientQueationFollowup: '患者报价跟进',
      remoteMonitoringFollowup: '远程监控跟进',
      medicalReportReview: '医疗报告审查',
      from: '从',
      to: '至'
    },
    appointmentList: {
      appointments: '预约时间',
      new: '新',
      confirmed: '确认',
      confirm: '确认',
      reschedule: '改期',
      cancel: '取消',
      rescheduleAppointment: '重新安排预约',
      rescheduledDate: '改期日期',
      rescheduledTime: '改期时间',
      noSlots: '在所选择的日期没有空位',
      rescheduleNote: '重新安排给病人的笔记',
      submit: '提交',
      confirmAppointmtent: '确认预约（可选）',
      selectAppointmtntType: '选择约会类型',
      clinicConsultation: '诊所咨询',
      videoConsultation: '视频咨询'
    },
    appointmentFilter: {
      all: '所有',
      confirmed: '已确认',
      newOrReschedule: '新增或重新安排',
      cancelled: '取消',
      concluded: '结论',
      video: '视频',
      clinic: '诊所',
      allPracticeLocation: '所有练习地点',
      allDepartment: '所有部门',
      allServices: '所有服务',
      VideoCons: '视频咨询（15）分钟',
      appointmentFilter: '预约过滤器',
      clinicSummary: '临床总结',
      practiceLocation: '实习地点',
      department: '部门',
      healthcareProvider: '医疗服务提供方',
      service: '服务',
      appointmentStatus: '预约状态',
      clear: '明确',
      apply: '应用'
    },
    setClinicConsultation: {
      setClinicConsultation: '诊所咨询',
      done: '完成了',
      service: '服务',
      practiceLocation: '实习地点',
      showConsultationTimings: '显示咨询时间',
      from: '从',
      to: '至',
      patient: '患者',
      phonenumber: '电话号码',
      reasonforAppointment: '预约理由',
      reasonPlaceholder: '输入设置患者预约的原因'
    },
    consultationTimings: {
      monday: '星期一',
      tuesday: '星期二',
      wednesday: '星期三',
      thursday: '星期四',
      friday: '星期五',
      saturday: '星期六',
      sunday: '星期日',
      timing: '*时间显示在（IST = UTC + 05：30）',
      consultationTimings: '咨询时间',
      done: '完成了',
      service: '服务',
      practiceLocation: '实习地点'
    },
    userProfile: {
      profile: "个人资料",
      yourDetails: "你的资料",
      contactInfo: "联络资料",
      manager: "经理",
      phoneNumber: "电话号码",
      about: "关于",
      dashboard: "仪表板",
      experience: "经验",
      accomplishment: "成就",
      course: "课程",
      language: "语言",
      projects: "专案",
      interests: "兴趣爱好",
      yourDashboard: "您的仪表板",
      privateToYou: "私人给你",
      whoViewedYourProfile: "谁查看了您的个人资料",
      postViews: "发表意见",
      searchAppearance: "搜索外观",
      carrerInterests: "职业兴趣",
      chooseTypeOpportunity: "选择您想与之联系的机会类型",
      salaryInsights: "薪资见解",
      salaryInsightsNote: "了解薪水与社区其他人的比较",
      editProfile: "Edit Profile",
      firstName: "名字",
      lastName: "姓",
      headline: "标题",
      countryRegion: "国家/地区",
      provinceState: "省/州",
      cityDistrice: "城市/地区",
      save: "保存",
      takePhoto: "拍照...",
      chooseFromGallery: "从图书馆挑选...",
      cancel: "取消",
      addExperience: "增加经验",
      title: "标题",
      employmentType: "雇佣类型",
      location: "位置",
      currentlyWorking: "我目前担任这个职位",
      startDate: "开始日期",
      endDate: "结束日期",
      description: "描述",
      Connections: "连接数"
    },
    betterMe: {
      requestFeedback: '要求反馈',
      sendFeedback: '发送反馈',
      feedbackRequests: '反馈要求',
      history: '历史',
      betterMe: '更好的我'
    },
    sendFeedback: {
      suggestedColleagues: 'Suggested Colleagues',
      findColleagues: 'Find Colleagues',
      sendFeedback: 'Send Feedback'
    },
    feedbackRequests: {
      answerRequest: 'Answer Request'
    },
    history: {
      received: 'Received',
      sent: 'Sent',
      loading: 'Loading'
    },
    takePart: {
      takePart: 'Take Part',
      whenDo: 'When do you prefer to do the Business workshop?',
      beingAble: 'Being able to generate and identify more ideas helps companies grow more quickly, stay relevant, and drive new trends.'
    },
    createTakePart: {
      createTakePart: 'Create Take Part',
      create: 'Create',
      chooseACardType: 'Choose a card type',
      tellUsYourWhy: 'Tell us your why',
      selectGroup: 'Select group to share card',
      what: 'WHAT?',
      why: 'WHY?',
      who: 'WHO?',
    },
    createCardReason: {
      createardReason: 'Why are you creating this card?',
      ansYes: 'Ans: Eg. Yes',
      ansNo: 'Ans: Eg. No',
      giveMoreDetails: 'Give More detail to this card',
      cardDetails: 'Card Details'
    },
    selectGroups: {
      chooseCardType: 'Choose Card Type',
      next: 'Next'
    },
    starMeUpChooseType: {
      sendAStar: 'Send A Star',
      selectedColleague: 'Selected Colleague',
      selectedGroups: 'Selected Groups/Colleague',
      placeHolder: 'Please tell us the reason you are recognizing your colleague',
      writeAComment: 'Write A Comment',
      send: 'Send'
    },
    starMeUpDashboard: {
      kudos: 'KUDOS',
      actEthecally: 'ACT ETHICALLY',
      teamPlayer: 'TEAM PLAYER',
      constantlyInnovate: 'CONSTANTLY INNOVATE',
      excellence_in_your_work: 'EXCELLENCE IN YOUR WORK',
      think_big: 'THINK BIG',
      have_fun: 'HAVE FUN',
      sendBy: 'send By',
      thisIsTextComment: 'This is text comment'
    },
    addGroup: {
      postToGroup: 'Post to group',
      selectColleague: 'Select Colleague',
      next: 'Next',
      startBy: 'Start by picking members for your groups.',
      emailPlaceholder: 'Type an email address'
    },
    createGroup: {
      create: 'Create',
      groupName: 'Group Name',
      financeLeadPlaceholder: 'Ex. Finance Leads',
      groupType: 'Group type and privacy',
      description: 'Description (Optional)',
      descriptionPlaceholder: 'Tell your member what your group is for eg. team planning, or organising a space mission.',
      groupMembers: 'Group Members'
    },
    events: {
      events: 'Events',
      today: 'Today',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      previous: 'Previous',
      participents: 'Participents'
    },
    createEvent: {
      createEvent: 'CreateEvent',
      selectAvatar: 'Select Avatar',
      generalTeamMeeting: 'General Team Meeting',
      startDate: 'Start Date',
      startTime: 'Start Time',
      pickTime: 'Pick a time',
      endDate: 'End Date',
      endTime: 'End Time',
      location: 'Location',
      description: 'Description',
      guestCan: 'Guests can invite coworkers',
      cancle: 'CANCLE',
      create: 'CREATE',
      eventName: 'Event Name',
      addPhoto: 'ADD PHOTO'
    },
    eventDetails: {
      going: 'Going',
      mayBe: 'Maybe',
      invited: 'Invited',
      saySomething: 'Say Something...',
      photo: 'Photo',
      recentActivity: 'RECENT ACTIVITY',
      joinPod: 'Join Pod',
      attending: 'Attending :'
    },
    updateStatus: {
      updateStatus: 'Update Status',
      post: 'Post',
      photoVideo: 'Photo/Video/Screenshot',
      goLive: 'Go Live',
      checkIn: 'Check In',
      feelingActivity: 'Feeling/Activity/Sticker',
      tagFriends: 'Tag Friends',
      whatsOnYourMind: 'Whats on your mind?'
    },
    tagMembers: {
      tagMembers: 'Tag Members',
      done: 'DONE',
      searchGroups: 'Search Groups'
    },
    inviteColleague: {
      findPhone: 'Find phone contacts',
      pendingInvites: 'Pending Invites',
      invite: 'INVITE',
      inviteColleague: 'Invite Colleague',
      enterEmail: 'Type an email address'
    },
    peopleToFollow: {
      peopleToFollow: 'People To Follow'
    },
    home: {
      newsFeed: 'News Feed',
      writePost: 'Write Post'
    },
    postToGroup: {
      postToGroup: 'Post to a group',
      searchGroups: 'Search Groups',
      yourTopGroups: 'Your top groups',
      commonDiscussion: 'Common Discussion',
      socialDiscussion: 'Social Discussion',
      general: 'General',
      flowDiscussion: 'Flow Discussion',
      uiUx: 'UI/UX'
    }
  }
})

export default strings