const skills = [
  { name: 'Cloud Computing' },
  { name: 'Artificial Intelligence' },
  { name: 'Analytical Reasoning' },
  { name: 'People Management' },
  { name: 'UX Design' },
  { name: 'Mobile Application Development' },
  { name: 'Video Production' },
  { name: 'Sales Leadership' },
  { name: 'Translation' },
  { name: 'Audio Production' },
  { name: 'Natural Language Processing' },
  { name: 'Scientific Computing' },
  { name: 'Game Development' },
  { name: 'Social Media Marketing' },
  { name: 'Animation' },
  { name: 'Business Analysis' },
  { name: 'Journalism' },
  { name: 'Digital Marketing' },
  { name: 'Industrial Design' },
  { name: 'Competitive Strategies' },
  { name: 'Customer Service Systems' },
  { name: 'Software Testing' },
  { name: 'Data Science' },
  { name: 'Computer Graphics' },
  { name: 'Corporate Communications' },
  { name: 'Creativity' },
  { name: 'Persuasion' },
  { name: 'Collaboration' },
  { name: 'Adaptability' },
  { name: 'Time Management' },
  { name: 'Data Analysis' }
]

module.exports = skills