export const appointmentConstants = {
  FETCH_APPOINTMENTS_BEGIN: 'FETCH_APPOINTMENTS_BEGIN',
  FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',
  FETCH_APPOINTMENTS_FAILURE: 'FETCH_APPOINTMENTS_FAILURE',
  SET_APPOINTMENT: 'SET_APPOINTMENT',
  DELETE_APPOINTMENTS: 'DELETE_APPOINTMENT',
  EDIT_APPOINTMENT: 'EDIT_APPOINTMENT',
};
