export const notesConstants = {
  FETCH_NOTES_BEGIN: 'FETCH_NOTES_BEGIN',
  FETCH_NOTES_SUCCESS: 'FETCH_NOTES_SUCCESS',
  FETCH_NOTES_FAILURE: 'FETCH_NOTES_FAILURE',
  SET_NOTE: 'SET_NOTE',
  DELETE_NOTES: 'DELETE_NOTE',
  EDIT_NOTES: 'EDIT_NOTES',
};
